{
    "网络已断开": "Network disconnected, connect to the server failed",
    "确定退出客户端吗:": "Are you sure to exit the client ?",
    "退出": "Exit",
    "删除角色": "Delete role",
    "OEM_UPGRADE_MESS": "Detect new resource，the client will automatically restart after update is finished, please wait...",
    "UPGRADE_MESS_WINDOWS": "Updates are detected, the computer will automatically reboot after upgrade, upgrade immediately ?",
    "关闭终端同时关闭桌面": "Close desktop while closing terminal",
    "关闭桌面同时关闭终端": "Close terminal while closing desktop",
    "个人桌面关机": "Personal desktop shutdown mode",
    "教学桌面关机": "Teaching desktop shutdown mode",
    "开机自启": "Startup in booting",
    "全屏可退出": "Able to exit full screen",
    "窗口模式": "Window Mode",
    "当前版本号": "Current Version",
    "终端名称": "Terminal Name",
    "未升级组件详情": "Not upgraded component details",
    "升级": "Upgrade",
    "教室/所有人": "Classroom/Owner",
    "正在连接服务器": "connecting server...",
    "所有": "All",
    "数据盘清除": "Data disk clear",
    "系统盘还原": "System disk restore",
    "最佳分辨率": "Best resolution",
    "最佳": "Best",
    "t-8": "REGISTER_TEMPLATE",
    "教室重复": "The IP range is the same with classroom XXX,please fill in again",
    "有线": "Wired",
    "REGISTER_FAILED": "Register failed",
    "自动进入场景": "Will auto log in",
    "新密码与旧密码相同": "The new password is the same with the old",
    "WEBSITE_init": "www.os-easy.com",
    "WEBSITE_login": "WWW.OS-EASY.COM",
    "WEBSITE_login_a": "http://www.os-easy.com",
    "2UPGRADEMESS": "Please ensure the client is running and successfully connect to the server,the client will reboot after upgrade,confirm to upgrade now ?",
    "UPGRADE_MESS_2": "System is upgrading, please do not shut off the power, the system will automatically restart after a successful upgrade",
    "UPGRADE_MESS_1": "Detected a new version, whether to upgrade immediately?",
    "重试": "retry",
    "不支持": "Unsupported",
    "UPGRADEMESS": "After upgraded, you need to restart the server to take effect,  upgrade immediately?",
    "查看未升级组件详情": "Not upgraded component details",
    "立即升级": "Upgrade Now",
    "已升级组件数/组件总数": "Upgrade components/Total components",
    "已连接": "Connected",
    "正在连接": "Connecting",
    "无线": "Wifi",
    "所有教室": "All",
    "REGESTER": "Registering...",
    "终端结束IP": "Default terminal end IP",
    "终端起始IP": "Default terminal start IP",
    "终端IP范围": "Default terminal IP range",
    "桌面IP段": "Desktop IP range",
    "系统包": "System package",
    "选择类型": "Select type",
    "软件包": "Software package",
    "无可注册模板": "No template to register",
    "模板注册": "Register Template",
    "注册": "Register Template",
    "虚拟机自助": "Virtual machine self service",
    "重启确认": "Reboot template",
    "不能超过50位字符": "Not more than 50 characters",
    "系统获取": "System Gain",
    "静态IP": "Stastic IP",
    "网络连接": "Network",
    "不是一个可接受的文件类型": "Is not an accepted file type",
    "文件为空": "Is empty",
    "超出文件大小限制": "Exceeded file size limit",
    "重启服务器生效": "Restart the server to take effect after modified",
    "AUTHROIZE_USER_TIP": "Please authorize administrator",
    "授权管理用户": "Authorize Administrator",
    "UPDATE_TEMPLATE_TIP": "Close the edit window directly, can temporarily not update the template, and save your updated content",
    "UPDATE_TEMPLATE": "The virtual machine will be closed,confirm to update template?",
    "角色管理": "Role manage",
    "管理范围": "Management scope",
    "权限分配": "Permission distribution",
    "编辑角色": "Edit role",
    "新增角色": "Add role",
    "修改时间": "Modification time",
    "修改人": "Modifier",
    "授权管理员数": "Authorized number",
    "角色名": "Role name",
    "角色": "Role",
    "优先启用HA服务器": "Priority to enable HA server",
    "启用全局HA": "Enable global HA",
    "选择日期": "Select a date",
    "选择周几": "Select a week",
    "不存在HA服务器": "There is no HA server",
    "请选择HA服务器": "Please select a server to HA",
    "启用HA": "Enable HA",
    "POOL_TIP": "Please select a management scope",
    "ROEL_TIP": "The role binded with administrator, unable to delete",
    "DELETE_ROLES2": "'{{1}}' associated with administrators and can not be deleted",
    "DELETE_ROLES1": "Confirm to delete '{{1}}' ?",
    "PERMISSION_TIP": "Please select a permission",
    "vdiTerminalconfigureName_TIP": "Can not modify name under off state in the selected terminals",
    "新增域": "Add Domain",
    "持续开机时间": "Running Time",
    "FORMAT": "Format",
    "ping包数": "Ping packets",
    "开始更新": "Start update",
    "SYSTEMUPDATE3": "System is upgrading, please do not turn the power off or remove the usb flash drive, system will automatically restart after a successful upgrade",
    "SYSTEMUPDATE2": "Upgrade file not detected, please update again",
    "空间不够": "Out of disk space",
    "SYSTEMUPDATE1": "Please insert the upgrade usb, click update to start the update",
    "重新配置序列号": "< Reconfigure the serial number",
    "序列号配置成功": "Configuration is successful, your serial number is",
    "手动输入": "Custom",
    "序列号自动加1": "Auto adding one",
    "终端排序": "Terminal sorting",
    "RETRY": "Retry",
    "TIMEOUT": "Timeout",
    "同步完成": "Complete",
    "TERMINAL_FAIL_TIP": "The request for terminal timeout!",
    "不可编辑": "IP is being used，unable to edit",
    "确定重启吗": "Confirm to restart?",
    "确定关机吗": "Confirm to shutdown?",
    "注销自动登录用户": "Log off automatically logged",
    "CPU信息": "CPU",
    "内存容量": "Memory capacity",
    "硬盘容量": "Hard disk capacity",
    "版本号": "version",
    "产品名称": "Product Name",
    "桌面属性": "desktop property",
    "系统属性": "system property",
    "获取": "obtain",
    "正在获取": "accessing..",
    "手动配置": "manual configuration",
    "个人桌面登录": "Personal desktop login",
    "请选择教学桌面": "Please select teaching desktop",
    "自动进入桌面": "Will auto log in",
    "请选择个人桌面": "Please select personal desktop",
    "用户名或密码不能为空": "The user name or password cannot be empty",
    "密码修改成功": "Password update successful, please log in again",
    "格式不正确": "Incorrect format, please reenter",
    "两次输入密码不一致": "Entered passwords differ,please reenter",
    "连接超时": "Timeout,please retry",
    "注销失败": "Logoff failed",
    "注销成功": "Logoff  successful",
    "请输入1024-65535之间的端口号": "The port number show between 1024-65535",
    "输入序号需大于起始序号": "The number should be equal or greater than the starting number",
    "请检查网络配置": "Failed to connect server，please check  your network config",
    "连接服务器失败": "Failed to connect server",
    "保存失败": "Save failure",
    "保存成功": "Save successful",
    "密码错误": "Password is error",
    "COPYRIGTH": "COPYRIGHT:OS-EASY.COM",
    "SETTERMINAL_TIP": "Note: Please restart the terminal after the modification of parameter setting",
    "ABOUT_NAME": "Os-easy Cloud Class",
    "h-3": "CHECK_MEMORY",
    "h-2": "CHECK_KVM_SUPPORT",
    "h-1": "CHANGE_HOST_IP",
    "s-3": "SNAPSHOT_DELETE",
    "s-2": "SNAPSHOT_TAKE",
    "s-1": "SNAPSHOT_RESTORE",
    "t-7": "SYNC_TEMPLATE",
    "t-6": "CLONE_TEMPLATE",
    "t-5": "INSTALL_COMPLETE",
    "t-4": "CREATE_TEMPLATE",
    "t-3": "DELETE_IMAGE",
    "t-2": "UPDATE_TEMPLATE",
    "t-1": "UPDATE_MODE_INSTANCE",
    "i-19": "RESET_MODE_VM",
    "i-18": "LIVE_MIGRATION",
    "i-17": "DISABLE_USBREDIR",
    "i-16": "ENABLE_USBREDIR",
    "i-15": "DISABLE_ROLLBACK",
    "i-14": "ENABLE_ROLLBACK",
    "i-13": "CHANGE_INSTANCE_IP",
    "i-12": "CHANGE_MEDIA",
    "i-11": "DESTORY_VM",
    "i-10": "RESIZE_DISK",
    "i-9": "HIBERNATE",
    "i-8": "UNPAUSE",
    "i-7": "PAUSE",
    "i-6": "CREATE_VM",
    "i-5": "REBOOT_VM",
    "i-4": "RESIZE",
    "i-3": "SAVE_TEMPLATE_VM",
    "i-2": "SHUTDOWN_VM",
    "i-1": "START_VM",
    "REPAIR": "Repair",
    "速度": "Speed",
    "UPLOADING": "Uploading...",
    "模板分布": "Template distribution",
    "SET_RESOLUTION": "System will restart automatically and save the settings, confirm to save?",
    "NOWEEK": "Not yet arrange class time, please arrange class time first!",
    "OUTOFFSCHULE": "The current time not in the class time!",
    "进度": "Progress",
    "设置分辨率": "Set the resolution",
    "登录终端名/IP": "Terminal name/IP",
    "持续运行时间": "Running Time",
    "禁用启用": "Disable/Enable",
    "调整范围": "Amend",
    "MAKING_SEED": "Making seed...",
    "使用NTP": "Use NTP",
    "城市": "City",
    "区域": "District",
    "麦克风": "Microphone",
    "音量": "Volume",
    "导出日志": "Export Log",
    "系统更新": "Update System",
    "重启系统": "Reboot System",
    "声音": "Voice",
    "属性": "Attribute",
    "持续发送ping包": "Continue to send ping packets",
    "尝试修复": "Try to repair",
    "地址": "Address",
    "字节长度": "Byte Size",
    "IP地址": "IP Address",
    "静态配置": "Static Configuration",
    "配置": "Configure",
    "网络诊断": "Network Diagnosis",
    "网络设置": "Network Settings",
    "端口": "Port",
    "旧密码": "Old Password",
    "修改密码": "Change Password",
    "保存密码": "Save Password",
    "每次不还原": "Every time not restore",
    "每次还原": "Every time restore",
    "返回信息格式错误": "Return error message format",
    "新建失败": "error",
    "TEMP_SYNC_FAILED": "Sync failed",
    "TEMPLATE_SYNC_FAILED": "Send failed",
    "正在生成种子文件": "Making seed",
    "SYNC_INFOR": "Template \"{{1}}\" distribution info",
    "登录时间": "( login 5 seconds at least,not more than 9999 seconds)",
    "TITLE_NAME": "OS-EASY",
    "/user/domain/:id": "<ul><li> domain server to open the state, the user can perform the synchronization domain user operation. </li><li> default synchronization of the default synchronization domain user directory data. </li></ul>",
    "/user/domain": "<ul><li>The domain server IP must communicate with the management server IP, domain name and domain server IP match, and can perform the new domain operation.</li></ul>",
    "GOD_VERSION": "cloudClassEn",
    "查看同步信息": "View synchronization information",
    "-1": "All type",
    "正在作种": "Seeding",
    "正在下载": "Downloading",
    "外网IP": "Outer net ip",
    "NET": "Network",
    "networkTitle": "Network{{1}}",
    "等考模式": "RDP",
    "ip分配": "Ip assignment",
    "优先级": "Priority",
    "节点IP": "Node IP",
    "版本": "Version",
    "节点名称": "Node name",
    "0xFF": "Vendor Specific",
    "0xFE": "Application Specific",
    "0xEF": "Miscellaneous",
    "0xE0": "Wireless Controller",
    "0xDC": "Diagnostic Device",
    "0x11": "Billboard Device Class",
    "0x10": "Audio/Video Devices",
    "0x0F": "Personal Healthcare",
    "0x0E": "Video",
    "0x0D": "Content Security",
    "0x0B": "Smart Card",
    "0x0A": "CDC-Data",
    "0x09": "Hub",
    "0x08": "Mass Storage",
    "0x07": "Printer",
    "0x06": "Image",
    "0x05": "Physical",
    "0x03": "HID (Human Interface Device)",
    "0x02": "Communications and CDC Control",
    "0x01": "Audio",
    "0x00": "Use class information in the Interface Descriptors",
    "RULE_NAME": "Rule name",
    "API_CODE": "Error code :",
    "HOST_NAME_IS_NOT": "The host name is invalid",
    "USER_NAME_IS_NOT": "The user name is invalid",
    "扩容大小": "Increase size",
    "扩容模板C盘": "Expansion disk C",
    "TEMP_UNDO_TIP": "The template will be returned to the last time state, confirm to restore?",
    "撤销本次": "Undo",
    "TEMP_SAVE_TIP": "Please make sure the current template can be normal use,confirm to to save?",
    "PREFIX001": "Prefix + three-digit number",
    "PREFIX01": "Prefix + two-digit number",
    "PREFIX1": "Prefix + one-digit number",
    "PREFIX": "Prefix",
    "USERNAME_SAMETO_TEMPLATE": "The user name is the same with the template",
    "USER_NAME_IS_": "Preview:the user name is {{1}}",
    "DEFAULT": "default",
    "CONFIGURE_USER_NAME": "Configure user name",
    "ADVANCED": "advanced",
    "HOST_NAME_IS_": "Preview：the host name is {{1}}",
    "BEGIN_WITH": "Begin with number",
    "TYPE": "Type",
    "HSOT_NAME_CONFIG": "Configure host name",
    "使用配置": "configure RDP",
    "自由分配": "Auto",
    "CLASSROOM": "Classroom(network)",
    "编辑USB重定向": "Edit USB redirect",
    "TEMPLATE_CLONING": "Cloning...",
    "DELE_USB_TIP": "Confirm to delete the USB redirects?",
    "DELE_USB": "Delete USB redirect",
    "新增USB重定向": "Add USB redirect",
    "VID": "VID",
    "PID": "PID",
    "id": "ID",
    "WRONG_NAME": "Template name exists!",
    "vdiTerminalconfigure_TIP": "Can not set operating parameters under off state in the selected terminals",
    "TEM_UNDOSYNC": "Template will return to the last updated desktop status, Confirm to undo the last update?",
    "COPY_TEM": "Save template as",
    "MORE": "more",
    "UNDO_SYNC_TEM": "Undo the last update",
    "SUMMARY_HOST_DESC": "Total {{1}} , <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown\"></span> {{3}}",
    "SUMMARY_TITLE_NODE": "<span class=\"alone\">agent node<strong> {{2}} </strong></span>",
    "SUMMARY_TITLE_DESKTOP": "<span><em class='en en-t'> teaching desktop </em> <em class='en en-n'><strong> {{1}} </strong> </em></span> <span><em class='en en-t'> personal desktop </em> <em class='en en-n'><strong> {{2}} </strong> </em></span>",
    "SUMMARY_TITLE_CLIENT": "<span><em class='en en-t'> classroom </em> <em class='en en-n'><strong> {{1}} </strong> </em></span> <span><em class='en en-t'> terminal </em> <em class='en en-n'><strong> {{2}} </strong> </em></span>",
    "SUMMARY_DESKTOP_DESC": "Total {{1}} , <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown\"> </span> {{3}}",
    "SUMMARY_CLIENT_DESC": "Total {{1}} , <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown\"></span> {{3}}",
    "SUMMARY_ALL_CORE": "Total {{1}} physical core(s)",
    "SUMMARY_VCPU_CORE": "{{1}} virtual core(s) running",
    "SUMMARY_VCPU_TOTAL": "Total  <strong> {{1}} </strong> virtual core(s)",
    "SUMMARY_SIZE_TOTAL": "Total <strong> {{1}} </strong> GB",
    "SUMMARY_SIZE_USED": "{{1}} GB used",
    "SUMMARY_SIZE_FREE": "{{1}} GB available",
    "HOST_TOTAL_MESS": "{{1}} host(s), <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown\"> </span> {{3}}",
    "HOST": "Host",
    "查看桌面": "View desktop",
    "桌面修改": "Modify desktop",
    "存为模板": "Save as template",
    "桌面强制关机": "Forcefully shutdown desktop",
    "桌面自然关机": "Naturally shutdown desktop",
    "确定强制关闭桌面吗": "Confirm to shut down the desktop forcefully ?",
    "桌面重启": "Restart desktop",
    "桌面暂停": "Pend desktop",
    "桌面恢复": "Wake up desktop",
    "桌面删除": "Delete desktop",
    "桌面删除后无法恢复，确定删除桌面吗": "Unable to restore the desktop after you deleted, confirm to delete the desktop?",
    "确定恢复桌面吗": "Confirm to wake up the desktop?",
    "确定暂停桌面吗": "Confirm to pend the desktop?",
    "确定重启桌面吗": "Confirm to restart the desktop?",
    "确定自然关闭桌面吗": "Confirm to shut down the desktop naturally?",
    "确定强制关闭场景吗": "Confirm to shut down the scene desktop forcefully ?",
    "确定自然关闭场景吗": "Confirm to shut down the scene naturally?",
    "删除场景": "Deleted scenes",
    "删除场景无法恢复，确定删除场景吗": "Deleted scenes can not be recovered, confirm to delete scenes?",
    "存在未关机的桌面,仍然删除场景吗": "There is desktop in running state , confirm to delete the scene?",
    "主控节点": "Consoles",
    "计算节点": "Computing nodes",
    "教室": "Classroom",
    "终端": "Terminal",
    "概要": "Summary",
    "资源池": "Resource",
    "主机管理": "Host",
    "网络管理": "Network",
    "存储管理": "Storage",
    "桌面": "Desktop",
    "教学桌面": "Teaching desktop",
    "个人桌面": "Personal desktop",
    "模板": "Template",
    "教学模板": "Teaching template",
    "个人模板": "Personal template",
    "硬件模板": "Hardware template",
    "教室管理": "Classroom",
    "终端管理": "Terminal",
    "会话管理": "Session",
    "用户": "User",
    "管理用户": "Administrator",
    "普通用户": "Common user",
    "监控": "Monitor",
    "主机监控": "Host monitoring",
    "桌面监控": "Desktop monitoring",
    "告警信息": "Alarm information",
    "排课": "Timetable",
    "课程列表": "Course list",
    "系统": "System",
    "系统备份": "System backup",
    "系统 ISO": "Package",
    "系统升级": "System upgrade",
    "操作日志": "Operation log",
    "关于": "About",
    "帮助": "Help",
    "所有服务器": "All servers",
    "选择服务器": "Select server:",
    "新增": "Add",
    "编辑": "Edit",
    "删除": "Delete",
    "提交": "Submit",
    "重置": "Reset",
    "自定义": "Custom",
    "系统登录名生成策略": "Login named by",
    "完成": "Finish",
    "基本信息": "Basic Info",
    "虚拟硬件信息": "Virtual hardware information",
    "等考配置": "Configure RDP",
    "配置虚拟硬件": "Configure virtual hardware",
    "绑定用户": "Bind user",
    "下载日志": "download logs",
    "下载": "Download",
    "LOADING_TEXT": "Data is loading ...",
    "NO_MATCHING_DATA": "No matching data",
    "TEMPLATE_UPDATE_FAILED": "Update failed",
    "TEMPLATE_UPDATING": "Updating ...",
    "MAKING": "Installing ...",
    "BUILDING": "On creating...",
    "SYNCING": "Syncing ...",
    "已用/总大小": "used/total",
    "关联桌面数": "Associated desktop",
    "创建者": "Creator",
    "创建时间": "Create time",
    "新增教学模板": "Add teaching template",
    "新增个人模板": "Add personal template",
    "模板名": "Template name",
    "LENGTH_LIMIT": "{{1}} ~ {{2}} characters",
    "不能超过30位字符": "Not more than 30 characters",
    "1~5位数字": "1 ~ 3 digits",
    "2~20位英文和数字": "2 ~ 20 letters or digits",
    "请输入搜索内容": "Please input search content",
    "备份名为英文或数字": "Backup name must be letters or digits",
    "请输入模板名": "Please input template name",
    "请先选择宿主机": "Please select host first",
    "所有人": "Owner",
    "选择模板": "Select template",
    "处理器": "Processor",
    "内存": "Memory",
    "系统盘/数据盘": "System disk/data disk",
    "安装方式": "Install way",
    "自动安装": "Auto-install",
    "手动安装": "Manual installation",
    "AUTO_INSTALL_TIP": "Configure the correct secret key, user information, template in advance, the  template operating system will be automatically installed, suitable for unattended operation.",
    "MANUAL_INSTALL_TIP": "After the configuration wizard finished, you should install the OS in template, need to manually configure the secret key, user information during the installation, suit for unattended operation.",
    "选择ISO": "Select package",
    "配置系统详情": "Configure system info",
    "windows产品秘钥": "Windows product secret key",
    "要装的windows版本": "System version",
    "用户名": "User name",
    "密码": "Password",
    "COMPLETE_INFOR": "Congratulations, the basic information of the template has been configured successfully, click \"Finish\" button to start installing template",
    "确定": "OK",
    "取消": "Cancel",
    "更新桌面": "Update desktop",
    "UPDATE_DESKTOP_INFOR": "The following scenes will be updated, please check if all the associated desktops are shut down. (Note: update desktop will turn off the desktop and the corresponding scene, please manually turn on after the update finished)",
    "CPU": "CPU",
    "系统盘": "System disk",
    "数据盘": "Data disk",
    "新增硬件模板": "Add hardware template",
    "名称": "Name",
    "增加数据盘": "Increase data disk",
    "移除数据盘": "Remove data disk",
    "教室名称": "Classroom name",
    "当前终端数": "Terminal amount",
    "当前场景数": "Scene amount",
    "网络": "Network",
    "操作": "Operate",
    "编辑教室": "Edit classroom",
    "新增教室": "Add classroom",
    "分配教室": "Assign classroom",
    "排序": "Sort",
    "人工排序": "Sort manually",
    "自动排序": "Sort automatically",
    "设置终端": "Terminal setting",
    "修改终端名": "Modify name",
    "设置运行参数": "Parameter setting",
    "固定桌面IP": "Bind desktop IP",
    "唤醒": "Wake up",
    "关机": "Shutdown",
    "中断会话": "Terminate session",
    "终端名": "Terminal name",
    "登录序号": "Login sequence",
    "终端IP/MAC": "Terminal IP/MAC",
    "运行状态": "Status",
    "接入桌面": "Accessed desktop",
    "接入终端": "Accessed terminal",
    "接入时间": "Access time",
    "接入时长": "Connection time",
    "终端列表": "Terminal list",
    "开始排序": "Start sorting",
    "起始序号": "Start NO.",
    "完成排序": "Complete sorting",
    "模式": "Mode",
    "权限": "Strategy",
    "快捷键": "Shortcut",
    "个性化": "Personalization",
    "默认模式选择": "Default selection",
    "混合模式": "Mixed mode",
    "教学模式": "Teaching mode",
    "个人模式": "Personal mode",
    "自动登录": "Automatic login",
    "启用": "Enable",
    "秒": "Second",
    "Windows客户端": "Windows client operation mode",
    "开机启动": "Boot",
    "全屏不可退出": "Unable to exit full screen",
    "隐藏退出按钮": "Hide the exit button",
    "关闭桌面即关闭终端": "Close desktop that is to close terminal",
    "WINDOWS_SHOUCUTS_DESCRIBE": "Windowed desktop",
    "LINUX_SHOUCUTS_DESCRIBE": "Windowed desktop",
    "分辨率": "Resolution",
    "服务器IP": "Server IP",
    "动态密码": "Dynamic password",
    "超级密码": "Super password",
    "开始IP": "IP starts from",
    "终端名前缀": "Prefix of terminal name",
    "登录名": "User name",
    "姓名": "Full name",
    "电子邮箱": "Email",
    "联系电话": "Telephone",
    "上次登录IP": "Latest login IP",
    "导出": "Export",
    "新增管理用户": "Add administrator",
    "新增普通用户": "Add common user",
    "性别": "Sex",
    "男": "Male",
    "女": "Female",
    "类型": "Type",
    "管理员": "Administrator",
    "编辑管理用户": "Edit administrator",
    "编辑普通用户": "Edit common user",
    "教师": "Teacher",
    "CPU占用率": "CPU utilization rate",
    "网络上下行流量": "Upload/Download dataflow",
    "磁盘读写速度": "I/O speed",
    "进程": "Process",
    "桌面名称": "Desktop name",
    "桌面编号": "Desktop numbers",
    "桌面类型": "Desktop type",
    "状态：": "State:",
    "清空": "Empty",
    "编号": "No.",
    "内容": "Description",
    "确认密码": "Confirm password",
    "新密码": "New password",
    "存储": "Storage",
    "时间": "Time",
    "重启": "Restart",
    "关闭": "Shutdown",
    "恢复": "Recover",
    "高级": "Advance",
    "DESKTOP": "Desktop",
    "桥接": "Bridge",
    "IP范围": "IP range",
    "子网掩码": "Subnet mask",
    "网关": "Gateway",
    "是": "YES",
    "否": "NO",
    "主机": "Host",
    "主机：": "Host :",
    "刷新频率": "Refresh rate:",
    "用途": "Partition",
    "存储名": "Storage name",
    "存储服务器": "Storage server",
    "位置": "Location",
    "容量": "Size",
    "可用空间": "Available",
    "状态": "Status",
    "缓存区": "Buffer",
    "数据区": "Data partition",
    "系统区": "System partition",
    "正常": "Normal",
    "异常": "Abnormal",
    "准备中": "Preparing",
    "本地磁盘": "Local disk",
    "iscsi 磁盘": "iscsi disk",
    "网络文件系统": "Network file system",
    "FC 光纤存储": "FC optical storage",
    "高級管理": "Advance management",
    "服务": "Service",
    "root密码": "root password",
    "桌面设置": "Desktop setting",
    "服务名称": "Service name",
    "描述": "Description",
    "开关": "Operate",
    "日志": "Log",
    "场景桌面开机": "Boot",
    "场景桌面关机": "Shutdown",
    "强制关机": "Forcefully shutdown",
    "自然关机": "Naturally shutdown",
    "场景名": "Name",
    "所属教室": "Classroom",
    "激活": "Activate",
    "在线/桌面数": "Online / Total",
    "桌面模板": "Desktop template",
    "还原设置": "Restore type",
    "每次都还原": "Every time",
    "按周还原": "Per week",
    "按月还原": "Per month",
    "无还原设置": "Never",
    "开机": "Boot",
    "暂停": "Pause",
    "桌面名": "Desktop name",
    "OS/模板": "OS / template",
    "CPU/内存/数据盘": "CPU / memory / data disk",
    "宿主机": "Physical host",
    "开机状态": "On",
    "关机状态": "Off",
    "挂起状态": "Pending",
    "迁移状态": "Migration",
    "全部状态": "All",
    "创建中状态": "Creating",
    "错误状态": "Error",
    "异常状态": "Abnormal",
    "未知异常状态": "Unknown exception",
    "操作系统": "OS",
    "模板名称": "Template name",
    "返回": "Back",
    "系统登录名": "System login",
    "已分配": "Assigned",
    "分配对象": "Assign to",
    "已使用": "Used",
    "使用对象": "Used by",
    "说明": "Description",
    "类型-网关": "Gateway",
    "类型-桌面": "Desktop",
    "备份": "Backup",
    "备份文件名": "Backup file name",
    "大小": "Size",
    "备份时间": "Backup Time",
    "ISO名": "ISO name",
    "系统类型": "Type",
    "上传时间": "Upload time",
    "KEY_PATTERN": "Such as: 87VT2-FY2XW-F7K39-W3T8R-XMFGF",
    "支持": "Support",
    "Windows 7 系列": "Windows 7 Series",
    "当前版本": "The current version",
    "升级包": "Upgrade package",
    "操作者": "Operator",
    "操作内容": "Operation log",
    "操作时间": "Operation time",
    "网卡名称": "NIC name",
    "MAC地址": "MAC",
    "网卡": "NIC type",
    "网卡IP": "NIC IP",
    "默认网关": "Gateway",
    "管理台": "Console",
    "保存": "Save",
    "恢复主机": "Restore host",
    "选择主机IP": "Select host IP",
    "新增IP": "Add IP",
    "结束IP": "IP ends to",
    "新增存储": "Add storage",
    "存储类型": "Storage type",
    "所在服务器": "Local server",
    "路径": "Path",
    "存储服务器挂载路径": "Storage server mounting path",
    "搜索": "Search",
    "新建逻辑卷": "Create logical volume",
    "使用": "Use",
    "逻辑卷": "Logical volume",
    "使用者": "User",
    "修改桌面": "Modify the desktop",
    "关联用户": "Associated user",
    "设置静态IP": "Set static IP",
    "不分配": "Not allocated",
    "动态迁移": "Dynamic migration",
    "选择迁移主机": "Select host",
    "新增个人桌面": "Add personal desktop",
    "桌面数": "Desktop amount",
    "系统自动选择合适数量的IP给虚拟机": "----System  selects the appropriate amount of IP to virtual machine automatically",
    "起始IP": "The initial IP",
    "请选择一个个人桌面模板类型：": "Please select a personal template",
    "其它": "Other",
    "绑定规则": "Rule",
    "完全匹配": "Exactly match",
    "循环匹配": "Circularly match",
    "选择用户": "User",
    "从下表选择一个或多个用户": "Select (one or more)",
    "已选择用户": "Selected",
    "选择系统类型": "Select the system type",
    "分类": "System type",
    "模板类型": "Template type",
    "快照管理": "Snapshot management",
    "快照名": "Snapshot name",
    "快照描述": "Snapshot description",
    "新增快照": "Add snapshot",
    "新增教学场景": "Add teaching scene",
    "指定到教室": "Classroom",
    "请选择一个教学桌面模板类型：": "Please select a teaching desktop template type:",
    "周一": "Mon",
    "周二": "Tue",
    "周三": "Wed",
    "周四": "Thu",
    "周五": "Fri",
    "周六": "Sat",
    "周日": "Sun",
    "每月第几天": "The day",
    "USB使用": "Enable USB",
    "计算机名生成策略": "PC named by",
    "自定义规则": "Custom rules",
    "系统默认规则": "System default rules",
    "计算机名规则": "Rule",
    "系统登录名规则": "Rule",
    "修改场景": "Modify scene",
    "MESS_REBOOT": "Restart computer to take effect after the network modified!",
    "MESS_SAVEROOT": "root password:",
    "MESS_ROOTNEED": "Need to verify root password when enable services and download log etc advanced feature!",
    "MESS_MAXINSTANCE": "Maximum running desktop amount",
    "MESS_NORESTOREIP": "No recoverable host IP!",
    "MESS_NEWSTORAGE": "4-20  digits or letters",
    "MESS_DYNAMIC": "Does not exist migratory hosts!",
    "MESS_NEWPERSON1": "1. Default is not bound IP. 2 After successfully created, through the personal desktop -> desktop to modify reassign fixed IP",
    "MESS_NEWPERSON2": "----System will assign same amount IP(start IP from setting) in network pool to match virtual machine",
    "MESS_NEWPERSON3": "---- The amount of selected users must be equal to created desktops, a user corresponds to one desktop",
    "MESS_NEWPERSON4": "---- The amount of selected users must be less than or equal to  created desktops, a user corresponds to one or multiple desktops",
    "MESS_SNAPSHOT": "1. Snapshot does not support usb redirection",
    "MESS_SNAPSHOT2": "2.Able to add new snapshot only when the desktop is in running state",
    "MESS_SENCEALTER": "Only can modify this after the desktop closed",
    "硬件配置": "Configure hardware",
    "核": "core",
    "1~8核": "1 ~ 8 Core",
    "1核": "1 Core",
    "2核": "2 Core",
    "4核": "4 Core",
    "8核": "8 Core",
    "选择教室": "Select classroom:",
    "显示": "Show",
    "每排显示": "Each row show",
    "CLIENT_REQUSET": "Sending request ...",
    "可进入排序": "Available sort amount",
    "TEMPLATE_DESC": "<span class = \"totalmess\"> <strong> {{1}} </strong> template(s) ,  <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown \"> </span> {{3}} </span>",
    "CLIENT_DESC": "<strong> {{1}} </strong> terminal(s) , <span class = \"status16 running\" > </span> {{2}} , <span class=\"status16 shutdown\"></span> {{3}}",
    "CLIENTSORT_DESC": "Client {{1}} , <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown\" > </span> {{3}} ,",
    "编辑模板": "Edit template",
    "该模版未关联任何场景": "The template is not related to any scene",
    "下载模版": "Download template",
    "TEMPLATE_DELETE_TIP": "The template associated with other desktop, firstly delete these desktops",
    "删除模版": "Delete template",
    "CLIENT_TIP1": "Can not modify terminal name under off state",
    "CLIENT_TIP2": "Can not set operating parameters under off state",
    "CLIENT_TIP3": "Terminal has been waked up",
    "CLIENT_TIP4": "Terminal has been shut down",
    "CLIENT_TIP5": "Can not interrupt the session under off state",
    "CLIENT_TIP6": "Can not be deleted under boot state",
    "加载ISO": "Load package",
    "发送": "Send",
    "更新模板": "Update template",
    "保存模板": "Save template",
    "删除硬件模板": "Delete hardware template",
    "删除教学模板": "Delete teaching template",
    "删除个人模板": "Remove personal template",
    "NODELETE_TEACH_TEMPLATE": "'{{1}}' associated with other desktop and can not be deleted",
    "唤醒确认": "Wake up terminal",
    "CLIENT_TIPGROUP1": "Confirm to wake up '{{1}}' ?",
    "CLIENT_TIPGROUP2": "Confirm to close '{{1}}' ?",
    "CLIENT_TIPGROUP3": "Confirm to terminate '{{1}}' ?",
    "CLIENT_TIPGROUP4": "Confirm to delete '{{1}}' ?",
    "删除教室": "Delete classroom",
    "CLASSROOM_TIPGROUP1": "Confirm to delete '{{1}}' ?",
    "CLASSROOM_TIPGROUP2": "'{{1}}' associated scenarios or other terminals, cannot be deleted",
    "SESSION_TIPGROUP1": "Confirm to terminate the session?",
    "删除用户": "Delete user",
    "USER_TIPGROUP1": "Confirm to delete '{{1}}' ?",
    "ALARM_DELETE": "Confirm to delete  ?",
    "清空确认": "Empty alarm",
    "CLEAR_TIP": "Confirm to empty alarm information ?",
    "上一步": "Previous",
    "下一步": "Next",
    "PAGE": "Show {{1}} ~ {{2}}, total {{3}}",
    "退出系统": "Exit",
    "课时设置": "Class arrangement",
    "全选": "Select all",
    "单周": "Odd week(s)",
    "双周": "Dual week(s)",
    "清除全部课表": "Clear all courses",
    "保存修改": "Save changes",
    "编辑勾选的周次": "Edit selected week",
    "取消编辑": "Cancel editing",
    "编辑模式": "Edit mode",
    "CLASS": "Course {{1}}",
    "CLASS1": "Course {{1}}",
    "添加场景排程": "Add scene course",
    "SCHEDULES": "Drag the scene to corresponding course",
    "设置": "Settings",
    "学期开始时间": "Semester start time",
    "学期结束时间": "Semester end time",
    "清除课程表": "Clear all courses",
    "DELETE_SCHEDULE": "Confirm to clear all courses timetable for the current classroom?",
    "许可内容": "License info:",
    "MAX_CONTECT": "Maximum connection desktop : {{1}}",
    "PERIOD_TIME": "Expiry date: <strong> {{1}} </strong>, left:<strong> {{2}} </strong> days",
    "更新授权": "<strong>Activate </strong>",
    "许可协议": "The license agreement",
    "ABOUT1": "<strong>The rights of usage</strong> You have the rights to install this software in computers, and use this software in the business scope to show all software features.",
    "ABOUT2": "<strong>Technical support </strong> You have the rights to obtain comprehensive technical support from OS-easy Cloud Computing. For the purposes of this software in any doubts, the problems in the process of installation, you have the rights to consult from OS-easy Cloud Computing, and request OS-easy Cloud Computing to answer or solve it.",
    "ABOUT3": "<strong>Version update </strong> According to actual needs, you have the rights to use the updated version of the software. But it is required to pay the appropriate version update fee if OS-easy Cloud Computing has other requirements.",
    "ABOUT4": "<strong>General restriction</strong> You only have the rights to use this software features, have no rights to reverse engineering, decompiling or disassembling on this software, meanwhile no rights to do secondary development, derive new software on basis of the software.",
    "ABOUT5": "<strong>Backup</strong> Unless normal use or for your own file backup purposes, you have no right to copy all or any part of the software.",
    "ABOUT6": "<strong>Usage</strong> The scope of rights to use this software is limited to your organization. without a written permission from OS-easy Cloud Computing, you have no rights to transfer, permit, rent, lease, lend or gift to others, provide the software to any third party, or reproduce any of parts of the software, whatever this offered for business purposes or not.",
    "ABOUT7": "<strong>Duty</strong> You have the duty to take effective measures to constrain your company's staff or employees to abide by the terms and conditions of the relevant conventions.",
    "ABOUT8": "<strong>Statement</strong> Refers to this software, any malicious damage to your computer resources (including documents, procedures, and other data) feature settings. For the loss of profit, availability disappeared, business interruption, or any form of indirect, special, incidental or inevitable destruction, or any other claims when you are in the process of using this software, Wuhan OS-easy Cloud Computing Co., ltd, and its agent and sale staffs is not responsible for it.",
    "ABOUT9": "<strong>Intellectual property rights and confidentiality </strong> The software copyright which involves the rights of OS-easy trademarks, patent, proprietary technology, and other rights, all are belonged to the owner of Wuhan OS-easy Cloud Computing Co., ltd. You should well keep the logo appeared in the software, cannot delete or modify without authorization. You have the rights to use it within the scope of authorization, but have no right to transfer another person to use. You also have confidentiality obligation which involves Wuhan OS-easy Cloud Computing Co., ltd’s secrets.",
    "ABOUT10": "<strong>Others</strong> Matters not included in this software license agreement will be defined in other agreement or terms consulted by both parties. This software license agreement applies to the relevant laws of the People's Republic of China.",
    "ABOUT": "If you have installed, copied or through other ways to use this software, you are deemed to have agreed with the following terms and conditions, and have signed the \"software license agreement\" (hereinafter referred to as the \"agreement\") with Wuhan OS-easy Cloud Computing Co., ltd (hereinafter referred to as the \" OS-easy Cloud Computing \"). If you obtained any copies of the software through legal channels of OS-easy Cloud Computing, then you have rights and obligations as follows:",
    "LICENSE1": "Firstly, <a href='{{1}}'> export the hardware code file </a>, and save it.",
    "LICENSE2": "Provide the hardware ID file to the software provider or access <a href = \"http://activation.os-easy.com\" target = \"_blank\" > the official authorization application site </a>, to apply the authorization document.",
    "LICENSE3": "Click the below button to upload <span style = 'color: orangered'> license.txt </span>to update authorization.",
    "噢易云计算": "OS-easy Cloud Computing",
    "序号": "No.",
    "操作类型": "Operation type",
    "对象名称": "Object name",
    "开始时间": "Start Time",
    "结束时间": "End time",
    "操作人员": "Operator",
    "详细": "Detail",
    "安装方法": "Install",
    "配置硬件": "Configure  hardware",
    "第1周": "1st week",
    "第2周": "2nd week",
    "第3周": "3rd week",
    "第4周": "4th week",
    "第5周": "5th week",
    "第6周": "6th week",
    "第7周": "7th week",
    "第8周": "8th week",
    "第9周": "9th week",
    "第10周": "10th week",
    "第11周": "11th week",
    "第12周": "12th week",
    "第13周": "13th week",
    "第14周": "14th week",
    "第15周": "15th week",
    "第16周": "16th week",
    "第17周": "17th week",
    "第18周": "18th week",
    "第19周": "19th week",
    "第20周": "20th week",
    "第21周": "21th week",
    "第22周": "22th week",
    "第23周": "23th week",
    "第24周": "24th week",
    "第25周": "25th week",
    "第26周": "26th week",
    "周时间": "Termtime",
    "课程时间": "Course time",
    "/resource/host": "<ul> <li> When host is started it will automatically register to the management platform. </li> <li>After restore the deleted host, need to restart the host. </li></ul>",
    "/resource/network": "<ul> <li> Able to reset the network by network initialization</li> </ul>",
    "/desktop/scene": "<ul> <li> Teaching scene must be activated, so that its teaching desktops can only be used by the terminals. </li> <li> Multiple teaching scenes can be in activation state at the same time. </li> <li> Click on the scene can view the scenario desktop. </li> <li> There is 30 seconds remain time left when the terminals dis-connected abnormally. During the remain time, terminals can login to the original desktop. </li> <li> Delete teaching scene will interrupt and destroy all running desktops. </li> </ul>",
    "/resource/network/:id": "<ul> <li> The end of the IP can not 0, 1, 255. </li> <li> Please delete IP which cannot be used by virtual desktop from the list. </li> <li> An IP can be repeated assigned to multiple desktops, but can cause the desktop IP conflict when using IP simultaneously. </li> <li> If reset IP segment, the platform must be restarted to take effect. </li> </ul>",
    "/desktop/teach/:id": "<ul> \n<li>You can use the desktop without username and password,which has desktop restore function,Computer name change function and so on</li>\n<li> All the clients in the classroom can get a teach system immediately you active the scene</li>\n</ul>",
    "/desktop/personal": "<ul><li>Personal desktop can be login at any one terminal. </li> <li> Personal desktop bind with users, need to enter your user name and password when login. </li> <li>Power-on/shutdown personal desktop can be manually controlled by the user or administrator. </li> <li> Naturally shutdown requires the system may support it, if not installed system please use the forcefully shutdown. </li> <li> Modify in batch takes effect after reboot desktop. </li> <li> Save as template, modify the desktop requires desktop in power-off state. </li> <ul>",
    "/template/teach": "<ul><li> Update template will automatically sync the template to associated teaching desktop. </ul>",
    "/template/hardware": "<ul> <li> Hardware template is a shortcut to configure the virtual hardware. </li></ul>",
    "/terminal/client": "<ul> <li> Terminal will automatically register to the management when boot. </li> <li> Remote \"Wake up\" function needs client itself hardware support \"Wake on LAN\". </li> <li>\"Login sequence number\" is refer to the terminal sequence of physical location.  </li> </ul>",
    "/terminal/session": "<ul> <li> Session connection maximum number is refer to the license stipulated by the maximum number of connections. </li> <li> Interrupt session will cut off the connection between current terminals and the desktop. </li> </ul>",
    "/user/admin": "<ul> <li> Super administrator account is “admin”, the default initial password is “admin”. </li> <li> The management platform is used by administrator only. </li> </ul>",
    "/user/common": "<ul> <li> Common user is refer to who can use of client access desktop, but can't login management platform. </li> <li>The excel format how to import the user, please reference export excel format. </li> </ul>",
    "/scheduler/view": "<ul><li>For classrooms which set default hour for teaching desktop in each class, when time arrives, will automatically activate the default desktop; </li> <li> Select the individual week time, use the edit button to enter edit mode. Drag and drop the corresponding to the corresponding class desktop; </li> <li> Select several weeks time, is taking a week as a benchmark, can edit all selected week in batch; </li> </ul>",
    "/system/backup": "<ul><li> It will cover the original backup file when file name repetition. </li><li> This function is only used for backup system database. </li></ul>",
    "/system/upgrade": "<ul> <li>The format of the system package is *. Bin.  </li> <li> Upload upgrade package, need to click on the <i class='fa fa-refresh'></i> to manual upgrade. </li> <li> after upgrading must restart the host to take effect. </li> </ul>",
    "/resource/console": "<ul><li>HA configuration requires master backup cannot be compute nodes, cannot run a virtual machine</li></ul>",
    "/resource/pool/:id": "<ul> \n<li>You can perform maintenance to the current online computing nodes, is not controlled by management platform, you can maintain this node manually</li> \n<li>You can execute restoration to the online compute nodes that has entered maintenance mode on management platform, desktops created before are not affected after restored this compute nodes</li> \n<li>System will default to use the local storage policies; users can change the storage policies</li> \n<li>In storage module, after adding remote storage, you can configure the remote storage policy here</li> </ul>",
    "/resource/pool": "<ul> \n<li>1.You can perform maintenance to the current online computing nodes, is not controlled by management platform, you can maintain this node manually</li> \n<li>2.You can execute restoration to the online compute nodes that has entered maintenance mode on management platform, desktops created before are not affected after restored this compute nodes</li> \n<li>3.System will default to use the local storage policies; users can change the storage policies</li> \n<li>4.In storage module, after adding remote storage, you can configure the remote storage policy here</li> </ul>",
    "/resource/storage": "<ul><li>Add remote storage here, you can configure the remote storage policies for each compute node in the resource management module</li></ul>",
    "DEFAULT_HELP_TEXT": "No related help content",
    "DESKTOP_TOTAL_MESS": "{{1}} desktop(s)",
    "每周第几天": "The day",
    "最大": "Maximum",
    "硬件信息": "Hardware information",
    "NEW_DESKTOP_EXAMPLE": "e.g: if input {{1}}, computer name will start from {{1}} 1",
    "NEW_DESKTOP_EXAMPLE2": "e.g: if input {{1}}, computer name will start from {{1}}-1",
    "DELETE_TEMPLATE_H": "Confirm to delete hardware template '{{1}}' ?",
    "DELETE_TEMPLATE_P": "Confirm to delete '{{1}}' ?",
    "DELETE_TEMPLATE_T": "Confirm to delete '{{1}}' ?",
    "皮肤一": "skin1",
    "皮肤二": "skin2",
    "TERMINAL_NAME_TIP1": "1.System will create terminal name in sequence.",
    "TERMINAL_NAME_TIP2": "2.Suggest to use short and unforgettable name for the prefix of terminal name.",
    "重启主机": "Restart host",
    "确定重启主机吗?": "Confirm to restart the host ?",
    "关闭主机": "Shut down host",
    "确定关闭主机吗": "Confirm to shut down the host ?",
    "BACKUP_DE": "Delete system backup",
    "BACKUP_DE_CONTENT": "Confirm to delete the backup?",
    "ISO_DELETE": "Delete ISO",
    "DELETE_ISO_CONTENT": "Confirm to delete the ISO?",
    "DELETE_LOG": "Delete log",
    "DELETE_LOG_CONTENT": "Confirm to delete the log(s)?",
    "DELETE_RIZHI": "Empty log(s)",
    "DELETE_RIZHI_CONTENT": "Confirm to empty the log(s)?",
    "RESTART_HOST": "Restart host",
    "RESTART_HOST_CONTENT": "Confirm to restart the host '{{1}}' ?",
    "DELETE_ALARM": "Delete alarm",
    "删除确认": "Delete terminal",
    "FIXED_IP1": "1. Assigned IP in batch  is to sequentially binding resource pool IP and client side IP",
    "FIXED_IP2": "2. Assigned IP will be no longer assigned to other client side",
    "确定删除主机吗": "Confirm to delete the host ?",
    "是否启用系统分配": "DHCP",
    "确定删除网络吗": "Confirm to delete the network?",
    "系统默认": "Default",
    "MESS_NEWPERSON5": "---- System will automatically assign available amount of IP to virtual machine",
    "查看模板": "View template",
    "MESS_NEWDESKTOP": "There is no available teaching  template!",
    "MESS_NEWDESKTOP2": "There is no available personal  template!",
    "INFOR_TIP": "Prompt",
    "选择语言": "Select Language",
    "上传系统包": "Upload",
    "上传授权文件": "Upload license",
    "导入": "Import",
    "vdiDesktopPersonalList_TIP1": "Please boot the none-updating desktop(s) in off-state",
    "vdiDesktopPersonalList_TIP2": "Please shut down the none-updating desktop(s) in running state",
    "vdiDesktopPersonalList_TIP3": "Please shut down the none-updating desktop(s) in running state",
    "vdiDesktopPersonalList_TIP4": "Please restart the desktop(s) in running state",
    "vdiDesktopPersonalList_TIP5": "Please pend the desktop(s) in running state",
    "vdiDesktopPersonalList_TIP6": "Wake up recover the desktop(s) in pend-state",
    "vdiDesktopTeachList_TIP1": "Please boot the desktop(s) in off-state",
    "vdiDesktopTeachList_TIP2": "Please shut down the desktop(s) in running state",
    "vdiDesktopTeachList_TIP3": "Please shut down the desktop(s) in running state",
    "vdiDesktopTeachList_TIP4": "Please restart the desktop(s) in running state",
    "vdiDesktopTeachList_TIP5": "Please pend the desktop(s) in running state",
    "vdiDesktopTeachList_TIP6": "Please wake up the desktop(s) in pend-state",
    "vdiDesktopSceneList_TIP1": "The selected scene already being activated, unable to delete",
    "newSceneDialog_TIP1": "Computer name and login name must be different",
    "newSceneDialog_TIP2": "The scene name already existed",
    "newPersonDialog_TIP1": "Desktop name already existed",
    "hostMoreDialog_TIP1": "IP and gateway is not in the same network segment",
    "newNetworkManageDialog_TIP1": "The number of start IP must be smaller than end IP",
    "newNetworkManageDialog_TIP2": "VLAN ID can not be repeated",
    "newNetworkIPDialog_TIP1": "The number of start IP must be smaller than end IP",
    "删除主机": "Delete host",
    "选择": "Select",
    "删除网络": "Delete network",
    "格式化": "Formatting",
    "查看详情": "View detail",
    "剩余": "available",
    "占用率": "Utilization rate",
    "已用内存": "Used memory",
    "读取": "Input",
    "写入": "Output",
    "S_周一": "Mon",
    "S_周二": "Tue",
    "S_周三": "Wed",
    "S_周四": "Thu",
    "S_周五": "Fri",
    "S_周六": "Sat",
    "S_周日": "Sun",
    "一月": "Jan",
    "二月": "Feb",
    "三月": "Mar",
    "四月": "Apr",
    "五月": "May",
    "六月": "Jun",
    "七月": "Jul",
    "八月": "Aug",
    "九月": "Sep",
    "十月": "Oct",
    "十一月": "Nov",
    "十二月": "Dec",
    "己用内存": "Memory",
    "删除存储": "Delete storage",
    "确定删除存储吗": "Confirm to delete the storage?",
    "上行": "Upload",
    "下行": "Download",
    "vdiResourceHostList_TIP1": "Only able to restart host when it is in running state",
    "vdiResourceHostList_TIP2": "Sorry, unable to delete control node",
    "vdiResourceHostList_TIP3": "Delete host successfully",
    "vdiTemplatePresonalDesktopList_TIP1": "Unable to delete the template when it assigned to other desktop(s)",
    "vdiTemplateTeachDesktopList_TIP1": "Unable to delete the template when it assigned to other desktop(s)",
    "vdiTerminalClientManage_TIP1": "Unable to set operation parameters when the terminal has been shut down",
    "vdiTerminalClientManage_TIP2": "Only able to set parameters when the machine is in running state",
    "vdiTerminalClientManage_TIP3": "Unable to modify terminal name when it has been shut down,",
    "vdiTerminalClientManage_TIP4": "Only able to modify terminal in running state",
    "vdiTerminalClientManage_TIP5": "Please select terminal",
    "vdiTerminalClientManage_TIP6": "The terminal has been waked up",
    "vdiTerminalClientManage_TIP7": "The terminal has been powered off",
    "vdiTerminalClientManage_TIP8": "Unable to terminate session when the terminal has been shut down",
    "vdiTerminalClientManage_TIP9": "Unable to delete when the terminal is in running state",
    "vdiTerminalClientManage_TIP10": "Unable to delete classroom when there is scene or terminal existed",
    "中断确认": "Terminate session",
    "Flash 插件没有安装": "Flash plugin is not installed",
    "文件名已存在": "The file name already exists",
    "上传的版本低于现在的版本": "The uploaded version is lower than the current version",
    "授权更新成功": "Update authorization successed",
    "授权更新失败": "Update authorization failed",
    "LICENSE_MESS_1": "New authorization has been taken effect, please view it after close this window and refresh the page.",
    "LICENSE_MESS_2": "Authorization file isn't matching to server hardware ID, please upload again after confirmation.",
    "LICENSE_MESS_3": "It is not a legal authorization file format or content, please check and upload again.",
    "删除IP": "Delete IP",
    "确定删除IP吗": "Confirm to delete the IP?",
    "项结果": "Item result",
    "存在未关机的桌面，仍然删除桌面吗": "There is desktop in running state , confirm to delete the desktop ?",
    "模板系统盘不能为0": "The system disk of template cannot be 0",
    "检查安装环境": "Check Environment",
    "系统初始化": "Initialization",
    "开始初始化": "Begin Initialize",
    "当前安装的版本为": "Current Version",
    "服务器": "Server",
    "导入默认数据": "Import Data",
    "建立超级管理员账户": "Import Administrator Account",
    "建立Projects": "Import Projects",
    "建立本地存储": "Import Local Disk",
    "建立默认教室": "Import Classroom",
    "建立默认硬件模板": "Import Hardware Template",
    "初始化客户端配置": "Import Client Configuration",
    "初始化网络": "Import Network",
    "初始化学期": "Initialize Semester",
    "MESS_INIT__FINISH": "Congratulations on system initialization is complete!<br>\n You can now",
    "登录": "Login",
    "第30周": "30th week",
    "第31周": "31th week",
    "第32周": "32th week",
    "第33周": "33th week",
    "第34周": "34th week",
    "第35周": "35th week",
    "第36周": "36th week",
    "第37周": "37th week",
    "第38周": "38th week",
    "第39周": "39th week",
    "第40周": "40th week",
    "进入管理台": "login as \"admin\"",
    "关机确认": "Shutdown terminal",
    "非系统盘": "Non-system disk",
    "不可重复添加已存在IP": "Existed IP will not be added repeatedly",
    "新增成功": "New IP added successfully!",
    "请输入合法数据": "Please enter valid data",
    "STORAGE_MESS": "{{1}} has been used by {{2}}({{3}})!",
    "文件不会被添加到队列中": "The file will not be added to the queue",
    "QUEUE_LIMIT_EXCEEDED": "The selected file number exceeds the upload limit ({{1}})",
    "INVALID_FILETYPE": "file:{{1}} \n'{{2}}' is not an accepted file type",
    "ZERO_BYTE_FILE": "File:{{1}} \nis empty！",
    "FILE_EXCEEDS_SIZE_LIMIT": "{{1}}\nexceeded file size limit {{2}}",
    "QUEUE_LIMIT_EXCEEDED2": "The number of your select file more than the queue size limit",
    "取消登录序号": "Cancel login sequence",
    "CANCEL_LOGINNUM": "Confirm to cancel login sequence?",
    "第27周": "27th week",
    "第28周": "28th week",
    "第29周": "29th week",
    "INSTALLED": "installation is complete",
    "高级管理": "Advance management",
    "选择网卡": "Choose NIC",
    "waringtype1": "Prompt",
    "waringtype0": "Warning",
    "waringtype-1": "Error",
    "操作结果": "Result message",
    "桌面重置": "Reset desktop",
    "确定重置桌面吗": "Confirm to reset the desktop?",
    "重置成功": "Reset successfully",
    "CLIENTMODIFY_SHUT": "Confirm to shut down ?",
    "CLIENT_TIP7": "Terminal has no access to the desktop",
    "SYSISOTIP1": "Please set the system type of ISO in system ISO first",
    "SYSISOTIP2": "There is no auto-install ISO",
    "1~10位英文和数字": "1 ~ 10 letters or digits",
    "INFOR_UPISO": "Begin to upload,please don't leave the page!",
    "ADMIN_TIP": "The user binded with desktop, unable to delete",
    "USER_TIPGROUP2": "'{{1}}' associated with other desktop and can not be deleted",
    "域用户": "Domain user",
    "域名": "Domain name",
    "服务器地址": "Server address",
    "域管理员": "Domain administrator",
    "关联用户数": "Associated users",
    "DOMAIN_TOTAL_MESS": "{{1}} domain(s), <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown\"> </span> {{3}}",
    "新增域控制器": "Add Domain Controller",
    "域控制器": "Domain Controller",
    "同步域用户": "Syncing domain user",
    "一键同步": "One button",
    "自定义同步": "Custom",
    "域登录名": "Domain username",
    "分组名": "Group Name",
    "编辑域控制器": "Edit domain Controller",
    "删除域控制器": "Delete domain Controller",
    "删除域用户": "Delete domain user",
    "更新域用户": "Update domain user",
    "选择分组": "Choose groups",
    "已选分组": "Chosed groups",
    "包含子目录": "Include subdirectories",
    "请选择需要同步的域分组": "Please select a domain packet synchronization:",
    "加入域": "Domain support",
    "所属域": "Domain",
    "SYNC_TEM": "Sync template",
    "SYNC_TEM_TIP": "Update desktop will close all the desktops associated with the current template and then update them all, Confirm to update desktop?",
    "USB_GROUP": "Class",
    "PID_LIMIT": "-1 or four hexadecimal number",
    "IS_REDIRECT": "Redirection",
    "USB_TYPE": "Type",
    "USB 重定向": "USB redirection",
    "资源": "Resource",
    "主控": "Console",
    "子网": "Subnet",
    "系统盘存储": "System disk storage",
    "数据盘存储": "Data disk storage",
    "倒数": "count backwards",
    "自动进入": "auto log in",
    "hybirdTip": "Tips: countdown 5 seconds at least,not more than 600 seconds",
    "自动进入桌面倒计时": "Auto log in desktop countdown",
    "个人桌面启用": "Personal desktop enabled",
    "教学桌面启用": "Teach desktop enabled",
    "MODE_TIP": "Note: In window mode of windows client, only close desktop while closing terminal in Teaching desktop shutdown mode effective, other desktop shutdown strategy is not effective",
    "高可用性": "HA",
    "桌面HA": "Desktop HA",
    "场景属性": "Scene properties",
    "运行配置": "Running configuration",
    "网络配置": "Network configuration",
    "宿主机配置": "Host configuration",
    "修改模板": "Modify template",
    "固定IP": "Fixed IP",
    "系统盘镜像": "System disk image",
    "数据盘镜像": "Data disk image",
    "无": "None",
    "场景排序": "Sort",
    "请选择一个教学模板": "Please select a teaching template",
    "域设置": "Domain",
    "请选择": "Please select",
    "计算": "Agent",
    "新增子网": "Add subnet",
    "资源池名称": "Name",
    "主机数量": "Host number",
    "添加存储": "Add storage",
    "子网数量": "Subnet number",
    "管理网络初始化": "Init network",
    "选择管理网络": "select network",
    "维护": "Maintain",
    "HA配置": "Config HA",
    "配置主控HA策略": "Config console HA",
    "主控HA": "Console HA",
    "主控节点管理IP": "Management IP of console",
    "备控节点管理IP": "Management IP of agent",
    "备控节点管理账户": "Management account of agent",
    "数据同步网络": "Synchronous data network",
    "浮动IP": "Float IP",
    "仲裁IP": "Arbitration IP",
    "敏感度(秒)": "sensitivity(s)",
    "测试连接": "Test contact",
    "添加计算节点": "Add agent",
    "配置存储": "Config storage",
    "本地网络": "Local network",
    "本地存储": "Local storage",
    "网卡类型": "Nic type",
    "磁盘": "Disk",
    "总容量()": "Total capacity{{1}}",
    "可用空间()": "Available capacity{{1}}",
    "品牌": "Brand",
    "硬盘": "Disk",
    "MESS_MAXSETINSTANCE": "Then maximum desktop number created at one time",
    "基础镜像存储设备": "Base image storage devices",
    "存储设备": "Storage device",
    "性能型存储设备": "Performance type storage devices",
    "容量型存储设备": "Capacity storage devices",
    "配置存储设备使用策略": "Configuration storage devices using strategy",
    "远端存储": "Remote storage",
    "已分配存储": "Allocated",
    "未分配存储": "Unallocated",
    "详情": "Detail",
    "维护中...": "Maintaining...",
    "创建中...": "Building...",
    "分配类型": "Allocation type",
    "子网名称": "Subnet name",
    "网络名称": "Network name",
    "创建子网": "New subnetwork",
    "编辑网络": "Edit network",
    "DELETE_NETWORK_COMFIRM": "Delete network will delete all subnets under the network, the desktop will not be able to use the network and confirm delete?",
    "DELETE_SUB_NETWORK_COMFIRM": "After deleting subnet, the desktop will not be able to use the subnet, confirm delete?",
    "外设配置": "Configuring Peripherals",
    "系统分配": "System allocate",
    "新增网络": "New network",
    "编辑子网": "Edit subnetwork",
    "策略名称": "Strategy name",
    "响应时间": "Response time",
    "启用状态": "Enable",
    "策略描述": "Strategy description",
    "选择桌面": "Select desktop",
    "中": "medium",
    "低": "low",
    "高": "high",
    "确定维护主机吗": "Confirm to maintain the host?",
    "确定恢复主机吗": "Confirm to recover the host?",
    "维护主机": "Maintain",
    "上移": "Up",
    "下移": "Down",
    "SCHO0L": "Schoolroom",
    "域用户列表": "Domain user list",
    "此资源池无可用主机": "The resource pool without host",
    "设置主控节点": "Set console",
    "管理服务器IP": "Server management IP",
    "INIT_COSOLE_MESS": "<p class=\"note\">Introductions:</p>\n<p class=\"note\">1.Only need to set one server in cluster as console node.</p>\n<p class=\"note\">2.If don't need to set this server as console node, please close this page.</p>",
    "INIT_AGENT_MESS": "<p class=\"note\">Introductions:</p>\n<p class=\"note\">1.After added console as compute nodes, the console will run as compute node at the same time.</p>\n<p class=\"note\">2.If need to configure the console and standby server HA, here cannot be added as compute node.</p>",
    "INIT_CONSOLE_LOADDING_MESS": "Setting console node takes about 5 minutes, please wait!",
    "主控设置": "Console setting",
    "将该主控添加为计算节点": "Setting the console as agent",
    "重置模板": "Reset template",
    "REST_TEMP_TIP": "Reset template will delete the original virtual machine templates to re-create virtual machine template, Reset or not?",
    "筛选": "filter",
    "上传包类型": "Package type",
    "清除消息": "Clear alarm",
    "消息": "alarm",
    "均衡创建": "Balance",
    "桌面计算机名/用户名": "computername/username",
    "INIT_AGENT_LOADDING_MESS": "Is adding agent,please wait for a moment!",
    "终端教学桌面": "Teaching",
    "终端个人桌面": "Personal",
    "REGISTER_TIP": "Is registered, you can close this dialog for other operation",
    "系统桌面": "System desktop",
    "新增系统桌面": "Add System Desktop",
    "系统桌面类型": "Type",
    "分布式文件系统服务器": "Distributed File System Server",
    "普通服务器": "Normal Server",
    "上传镜像": "Upload image",
    "创建桌面": "Create",
    "查看桌面详情": "View",
    "另存为": "Save as",
    "删除服务器": "Delete Server",
    "DELETE_SYSDESK_T": "Confirm to delete '{{1}}' ?",
    "系统桌面设置": "Desktop Settings",
    "选择透传设备": "PCI-E",
    "启动": "activate",
    "随宿主机服务器启动": "Along with the hosting",
    "配置桌面": "Desktop Settings",
    "编辑桌面": "edit",
    "桌面详情": "detail",
    "分布式存储服务器": "Distributed storage server",
    "vdiResourceHostList_TIPRECOVER": "Please confirm the host is in the maintain state",
    "无设备": "No Device",
    "vdiDesktopTeachList_TIP7": "Please comfirm the desktop is shutdown",
    "取消PCI设备透传": "Cancel the PCI device passthrough",
    "未启用": "unable",
    "解绑": "unbundling",
    "OUTER_IP_NOTE": "<p>1.If there is network address translator in router, need to save the external network IP so that to use all functions through public network</p>\n<p>2.If configured external IP for server NIC, need to save the external network IP so that to use all functions through public network.<p>",
    "vdiResourceHostList_TIPDELETE": "Please comfirm the host is active and there is no active VM",
    "vdiResourceHostList_TIPACTIVE": "Please comfirm the host is active",
    "CLONING_FAILED": "Cloning failed",
    "RESET_FAILED": "Reset failed",
    "CREATE_FAILED": "Create failed",
    "主控管理": "Control node management",
    "资源池管理": "Resource pool management",
    "新增资源池": "New resource pool",
    "配置属性": "Configure properties",
    "--请选择--": "-- Please select—",
    "继承网卡": "Inherited NIC",
    "解绑网卡": "Unbind NIC",
    "绑定网卡": "Bind NIC",
    "bond类型": "Bond type",
    "NETCARD": "NIC",
    "SCENE_CANCEL_COMFIRM": "Cancel to activate the scene will close all related desktops at the same time. Cancel or not?",
    "DELETE_HOST_COMFIRM": "The computing note can be deleted only when it is online and have no affiliated desktop ,no template or the computing node is offline, are you sure to delete?",
    "MAINTAIN_HOST_COMFIRM": "Entering maintenance mode will close all desktops created on compute nodes, close or not?",
    "桌面移动成功": "Desktop move successfully",
    "vdiBondNetcard_TIP1": "Please select two network cards to bind at least",
    "HA_NOTE": "When you enable HA, the IP will be set as floating IP",
    "对象": "Object",
    "rescheduled": "Perform the HA strategy",
    "存储用途": "Storage use",
    "桌面磁盘镜像存储": "Desktop disk-image storage",
    "本地文件共享存储": "Local file share storage",
    "存储管理节点": "Storage management node",
    "无可绑定网卡": "No network card can be bound",
    "LIMITE_LETTER": "2- 20 letters and numbers, must start with letter",
    "配置公共存储": "Configure public storage",
    "禁用": "disable",
    "INIT_COMPUTENODE_MESS": "The current host has been added as backup server or computing nodes, cannot be initialized; if you want to set the current note as the master please delete these notes on the original management platform or contact the administrator.",
    "TEM_CONFIG_TIP": "Note: Modify CPU and memory will be effect next time after the virtual machine power on",
    "MASKMODEL_WAITING_TIPS": "Restarting Server, please wait",
    "DESKTOP_MOVE_TIP1": "Please select the shutdown desktop which virtrual type is kvm and on the far-end storage to move",
    "SAVING": "Saving ...",
    "文件浏览": "Browse file",
    "vdiDesktopPersonalDomain_TIP1": "Choose non-domain joined and domain user desktop",
    "vdiDesktopPersonalDomain_TIP2": "Please select domain-joined desktop",
    "DOMAIN_EXIT_TIP": "Selected desktop will automatically exit domain in next boot, Are you sure?",
    "DOMAIN_EXIT_TIP2": "All desktops in the scene will automatically exit domain in next boot, Are you sure?",
    "加域": "Add domain",
    "退域": "Exit domain",
    "MESS_DOMAIN_LABEL": "Please select the joined domain",
    "MESS_DOMAIN_SID": "Modify desktop security identifier (SID)",
    "MESS_DOMAIN_CONTROLLER": "Domain controller does not exist!",
    "拟加入域": "It intends to join domain",
    "当前域": "Current domain",
    "域": "Domain",
    "总容量": "Total capacity",
    "镜像管理": "Image Management",
    "镜像类型": "Image type",
    "是否存在镜像": "The image has existed or not",
    "是否关联桌面": "Associated Desktop or not",
    "管理主机": "Management Host",
    "简体中文": "Simplified Chinese",
    "繁体中文": "Traditional Chinese",
    "所在宿主机": "Located host",
    "宿主机分布": "Host distribution",
    "HA宿主机范围": "HA host range",
    "所有桌面数": "All desktop amount",
    "MESS_NEW_HA": "Description: Here fliter the same network, HA image, storage configurations as previous HA host",
    "分发镜像": "Distribute image",
    "删除镜像": "Delete image",
    "正在删除": "Deleting",
    "正在分发": "Distributing",
    "分发失败": "Distribute failed",
    "重新分发": "Repeat distribute",
    "存储控制节点": "Storage control node",
    "自定义创建": "Custom",
    "数据盘还原": "Data disk restore",
    "正在请求": "Requesting ...",
    "查看桌面HA详情": "View Desktop HA Details",
    "修改桌面计算机名": "Modify desktop PC name",
    "删除系统桌面": "Remove system desktop",
    "TEM_EXIST": "The template exists related personal desktop, unable to  update",
    "存储详情": "Storage details",
    "计划任务": "Scheduled Task",
    "定时开关机": "Timing power on/off",
    "模板详情": "Template Details",
    "任务名": "Task name",
    "新增定时开关机": "Add timing power on/off",
    "时": "Hour",
    "分": "Minute",
    "执行时间": "Execution Time",
    "执行任务": "Execute the task",
    "数据盘镜像2": "Data disk image 2",
    "告警策略": "Alarm policy",
    "GPU加速": "GPU acceleration",
    "卷ID": "Volume ID",
    "备份配置": "Back up configuration",
    "保留数量": "Reserved Quantity",
    "自动备份": "Automatic backup",
    "备份周期": "Backup period",
    "每天": "Daily",
    "每周": "weekly",
    "备份路径": "Backup path",
    "启用GPU加速": "Enable GPU acceleration",
    "启用USB": "Enable USB",
    "SHUTOFF_TIP": "Template virtual machine is powered off",
    "shutdown_TEMPLATE_T": "Comfirm to close '{{1}}' template virtual machine?",
    "无可挂载数据盘": "No available data disk can be mounted",
    "是否自动进入桌面": "Whether to enter desktop automatically",
    "设置自动进入桌面": "Automatically enter desktop",
    "倒计时": "Countdown",
    "未获取到信息": "No obtained information",
    "显卡": "Graphic card",
    "设置桌面IP": "Set desktop IP",
    "取消桌面IP": "Unbind desktop IP",
    "CANCELIP_TIP": "Binding Desktop IP has been canceled",
    "CANCELIP_TIP1": "Unbind desktop IP for terminal '{{1}}'?",
    "编辑定时开关机": "Edit timing power on/off",
    "DELETE_PLAN_T": "Delete task '{{1}}'?",
    "DELE_PLAN_TIP": "Forbid to delete the being executed task",
    "确认删除吗": "Confirm delete?",
    "系统保留的备份文件数量": "The number of system backup files",
    "备份方式": "Backup method",
    "手动备份": "Manual backup",
    "已启用": "enable",
    "MONITOR_EMAILL_MESS": "If you have multiple E-mail addresses, a line separately for each email address",
    "更多详情": "More",
    "TIP_PLAN": "Tip: the boot task is for waking up teaching desktop of terminals",
    "hasStaticIP_TIP": "Has no available IP",
    "SCHEDUL_TIP": "Boot and shutdown time is the same",
    "确认删除存储吗": "Confirm to  delete the storage?",
    "执行格式化": "Format",
    "主控节点当前管理IP": "Current management IP",
    "主控节点新管理IP": "New management ip",
    "删除失败": "Delete failed",
    "新增bond": "Add bond",
    "网络类型": "Network type",
    "系统盘镜像存储设备": "System disk image storage device",
    "数据盘镜像存储设备": "Data disk image storage device",
    "系统盘存储设备": "System disk storage device",
    "数据盘存储设备": "Data disk storage device",
    "主机缓存设备": "Host cache device",
    "镜像存储": "Image storage",
    "增加": "Add &nbsp;",
    "删除2": "Delete &nbsp;",
    "配置全局告警": "Configure global alarm",
    "配置告警邮件": "Configure alarm email",
    "告警项": "Alarm item",
    "CPU利用率": "CPU utilization",
    "内存利用率": "Memory utilization",
    "磁盘使用空间": "Disk usage",
    "磁盘IO利用率": "Disk I/O utilization",
    "网络上下行速率": "Upload/Download speed",
    "持续": "Persist",
    "告警邮件": "Alarm email",
    "发送告警邮件": "Send alarm email",
    "新增告警策略": "Add alarm policy",
    "分钟": "Minute",
    "核心服务异常": "Core service exceptions",
    "计算节点离线": "Computing nodes offline",
    "主控高可用性": "Console HA",
    "桌面高可用性": "Desktop HA",
    "教学桌面运行时间": "Teaching desktop Running Time",
    "个人桌面运行时间": "Personal desktop Running Time",
    "系统授权日期": "System authorization date",
    "小时": "Hour",
    "天": "Day",
    "发件服务器地址": "Send server address",
    "发件人邮箱账户": "Sender email accounts",
    "发件人邮箱密码": "Sender email password",
    "测试邮件地址": "Test email address",
    "发送测试邮件": "Send test email",
    "查看告警策略": "View alarm policy",
    "不发送告警邮件": "Don't Send alarm email",
    "修改告警策略": "Modify alarm policy",
    "移动至": "Move to",
    "计算机名": "PC name",
    "挂载数据盘": "Mounte data disk",
    "虚拟化类型": "Virtualization type",
    "场景创建中": "creating scene",
    "IP池": "IP list",
    "DELETE_HOST_COMFIRM?": "The computing note can be deleted only when it is online and have no affiliated desktop ,no template or the computing node is offline, are you sure to delete?",
    "物理网络": "Physical network",
    "取消场景激活": "Cancel scene activation",
    "应用": "Apply",
    "删除数据盘": "Delete data disk",
    "无可用个人桌面": "Has no personal desktop",
    "选择目标主机": "Select target host",
    "桌面计算机名": "Desktop PC name",
    "教学场景": "Teaching scene",
    "立即备份": "Backup now",
    "桌面移动": "Desktop move",
    "DELETE_POOL_COMFIRM": "Confirm to delete resource?",
    "INIT_COSOLE_MESS2": "<p class=\"note\">Tips:</p>\n<p class=\"note\">1.Management network refers to the communication network between console node and computing node.</p>\n<p class=\"note\">2.Mirror network refers to the network used to distribute image between console node and computing node </p>",
    "创建数据网络": "data network",
    "映射网络适配器": "Map network adapter",
    "分布式虚拟交换机": "Virtual Switch",
    "数据网络": "Data network",
    "分布式虚拟交换机名称": "Name of distributed virtual switch",
    "镜像网络": "Mirror network",
    "按创建时间排序": "Sort by created time",
    "按模板名称排序": "Sort by template name",
    "管理网络": "Management network",
    "修改管理网络": "Modify management network",
    "修改镜像网络": "Modify mirror network",
    "修改": "Modify",
    "主机名": "Host name",
    "关联主机": "Associated host",
    "编辑分布式虚拟交换机": "Edit distributed virtual switch",
    "删除分布式虚拟交换机": "Delete distributed virtual switch",
    "DELETE_VIRTUALSWITCH": "Associate distributed virtual switch has not been associated data network can be deleted, confirm to delete?",
    "透传": "Transparent transmission",
    "设备名称": "Device name",
    "设备制造商": "Device vender",
    "所属主机": "Affiliated host",
    "透传到桌面": "Transparently transmit to desktop",
    "后台日志": "Background log",
    "主机 USB 设备": "Host USB device",
    "映射网卡": "Map network card",
    "ADD_AGENT_MESS": "<p class=\"note\">Tips：</p>\n<p class=\"note\">1.Management network refers to the communication network between console node and computing node.</p>\n<p class=\"note\">2.Mirror network refers to the network used to distribute image between console node and computing node</p>\n<p class=\"note\">3.Data network refers to the network used by virtual machine</p>",
    "ADD_AGENT_NOTE": "Be sure to configure a mirror network IP that can communicate with the IP on compute node, otherwise will Failed to create desktop or update template",
    "重新发现": "Rediscover",
    "映射网络设备器": "Map network device",
    "关联分布式虚拟交换机": "Associate distributed virtual switch",
    "立即进入": "Enter immediately",
    "首选": "Preferred",
    "备用": "Standby",
    "确认删除该bond设备吗": "Delete the bond device?",
    "继承IP": "Existing IP",
    "现有IP": "Existing IP",
    "指派网卡": "Assign network card",
    "D_UNBUNDLE_NETCARD_EXPLAIN1": "Can inherit IP to maintain network connectivity",
    "D_UNBUNDLE_NETCARD_EXPLAIN2": "Management network and mirror network must be inherited",
    "外网访问": "External network access",
    "NO_OUSIDEIP": "Not available compute node",
    "上传": "Upload",
    "上传安装包": "Upload installation package",
    "添加文件": "Add file",
    "本地网卡": "LocalAdd distributed virtual switch network card",
    "编辑映射网络适配器": "Edit mapping network adapter",
    "新增分布式虚拟交换机": "Add distributed virtual switch",
    "删除资源池": "Delete resource pool",
    "编辑资源池": "Edit resource pool",
    "Windows客户端1": "Windows client",
    "等待时间": "Waiting time",
    "与服务器连接断开后自动退出": "Exit automatically after disconnected from server",
    "测试镜像网络": "Test mirror network",
    "网络不通": "Network is disconnected",
    "网络堵塞": "Network jam",
    "网络连通": "Network is connected",
    "选择路径": "Select path",
    "新增关联主机": "Add associated host",
    "删除关联主机": "Delete associated host",
    "DELETE_VIRTUALSWITCHITEM": "After deleted the associated host, you cannot use the network on the distributed virtual switch if you create a desktop on the host, confirm to delete?",
    "无可用的关联主机网卡": "No available associated hosts and network cards",
    "USB_NOTE": "Note: USB 3.0 redirection can only be enabled when desktop OS is Windows 7 or above",
    "资源池删除": "Delete resource",
    "外网IP123": "Agent server IP",
    "编辑bond": "Edit bond",
    "vdi_checkping_error": "Failed to obtain network card information",
    "主控节点/计算节点": "Console node/compute node",
    "Hyper-V桌面连接方式": "Hyper-V desktop connection type",
    "terminalTips": "<ul> <li>Set windows client connecting Hyper-V model desktop：</li> <br> <li>RDP：</li><li>1. Terminal and desktops only support  windows 7 and above operation system</li><li>2.Terminal and remote desktop are able to communicate, adjust the connection quality automatically according to the network speed</li><li>3.the desktop network can not be changed during the connection, otherwise it will be disconnected</li><li>4.Native support for local video redirection</li> <br><li>VMConnect：</li><li>1.Terminal and desktop only support windows 8 and above operating system</li><li>2. Terminal needs to enable hyper-v function</li></ul>",
    "DELETE_BOND_IVALID_CONFIRM": "Network card is disabled, which may cause no responsible service, confirm or not?",
    "镜像网络无法连通": "Can not connect mirror network",
    "configHATestIPConfirm": "Please click 'test connection' button, confirm the arbitration IP network connectivity",
    "关闭排序": "Close",
    "随宿主机启动": "Along with the hosting",
    "磁盘共享到桌面": "Disk shared to desktop",
    "资源回收": "Resource reclamation",
    "时间同步": "Time synchronization",
    "断开连接": "Disconnect",
    "after-minutes": "after minutes, execute",
    "挂起": "Suspend",
    "更改": "Change",
    "after-hours": "after hours, execute",
    "与Internet时间服务器同步(s)": "Synchronized to the Internet Time Server",
    "服务器(E):": "Server:",
    "立即同步": "synchronization",
    "同步时间成功": "Synchronize time succeed",
    "时区": "Time zone",
    "关机提示": "Shutdown prompt",
    "是否进行一键关机？": "Execute one-click shutdown?",
    "执行周期": "Execution cycle",
    "确定退出客户端吗": "Are you sure to exit the client ?",
    "按月清除": "Per month",
    "按周清除": "Per week",
    "每次清除": "Every time",
    "不清除": "Never",
    "兼容模式": "qcow2",
    "高速模式": "raw",
    "数据盘格式": "Data disk format",
    "该网络同XXX网络重复，请直接修改该网络": "The network is repeat with XXX, please modify the network directly",
    "MESS_NEWNET2": "Delete vlan network need to restart the server,comfirm to delete?",
    "普通网络": "Normal",
    "网络IP池": "Network IP",
    "系统自动生成！": "Generate OS automatically!",
    "VLAN网络": "VLAN",
    "桥接网络": "Bridge network",
    "启用DHCP": "Enable DHCP",
    "启用NAT": "Enable NAT",
    "绑定IP": "Bind IP",
    "MESS_NEWSTORAGE2": "Input server IP,e.g :172.16.10.64",
    "上传iso": "Upload",
    "个": "cycles",
    "NO_UNIT": "",
    "ADD_NAME": "{{1}}",
    "新建资源池": "Add resource",
    "此教室所在资源池无可用主机": "The resource pool of classroom without host",
    "中文简体": "Chinese-Simplified",
    "中文繁体": "Chinese Traditional",
    "添加": "Add",
    "创建数据化网络": "Create a data network",
    "主控节点镜像网络IP": "Master node mirror network IP",
    "首选DNS": "Preferred DNS",
    "备用DNS": "Standby DNS",
    "外网访问范围": "Outside network access",
    "vdi_checkroot_error": "root password error",
    "init.import-img": "Select template image",
    "init.import-img-title": "You can import template system images with following two ways",
    "init.import-from-cloud": "Copy template system disk image to root directory of USB device, and connect with server, you can directly import it to template image library",
    "init.import-from-local": "Upload local template system disk image to server side through web page",
    "init.imported-img": "Imported images",
    "button.upload-img": "Local upload",
    "button.import": "Import",
    "button.scan": "Scan",
    "button.skip": "Skip",
    "init.register-teach-tmpl": "Register teaching template",
    "init.teach-tmpl-osimg": "System disk image",
    "init.teach-tmpl-name": "Template name",
    "init.teach-tmpl-name-len": "2~20 characters",
    "init.teach-tmpl-os": "Operating system",
    "init.teach-tmpl-net": "Network",
    "init.teach-tmpl-subnet": "Subnet",
    "init.register-tmpl": "Register template",
    "license-title": "You can activate now in following way or activate after trial:",
    "init.tryuse": "Activate after trial",
    "init.trytips": "15-day trial, 60 desktops can be connected simultaneously in maximum",
    "init.create-teach-scene": "Create a teaching environment",
    "init.desktop-num": "Fill in according to server configuration and teaching environment requirements",
    "client.msg.offline-1": "Disconnected with server network",
    "client.msg.offline-2": "s later, will switch to local system",
    "client.button.switchnow": "Switch now",
    "client.title.alert": "Alert",
    "button.import-by-server": "Import by server",
    "button.refresh": "Refresh",
    "quickdeploy.empty-imgs": "Current template image library is empty, needs to be imported by server or locally uploaded",
    "quickdeploy.helpmsg": "Note: For first-time deployment, a teaching desktop can be quickly and easily created by importing images and registering templates",
    "upload.remain": "estimated remaining time: {{1}} hours {{2}} minutes {{3}} seconds",
    "client.sort-success": "Sort succeed!",
    "client.client-order-msg": "Your terminal number is:",
    "forceAddHostTips": "When master node of a cluster cannot be recovered, a new cluster can be created by force adding compute nodes of original cluster to the new master node",
    "强制添加计算节点": "Force adding compute node",
    "按添加时间排序": "Sort by time added",
    "按名称排序": "Sort by name",
    "SAME_SCENE_NAME": "The teaching environment name already exists",
    "SAME_PERSONAL_NAME": "The Personal desktop name already exists",
    "filterHardTempTips": "This filter out the hardware templates that meet the following requirements: <br> 1. System disk capacity is larger or equal to the selected teach template system disk <br> 2. The data disk amount needs to be larger or equal to the selected tech template data disk amount <br> 3. Data disk capacity is larger or equal to the capacity of the selected tech template data disk, if there are two data disks, then compare in sequence<br><br>The configuration of the desktop created: <br>1. created tech desktop CPU and memory should be consistent with hardware template<br> 2. create consistent <br> 3. data disk amount and capacity should be consistent with hardware template ",
    "USBRedictTips": "<ul> <li> 1. Enable USB 3.0 redirection, then use USB 3.0 controller in desktop; </ li> <li> 2. Enable USB 2.0 redirection, use USB 2.0 controller in desktop; </li> <li> 3. Regardless of which type of redirection is enabled, USB device of any protocol type can be connected to terminal interface of any protocol for redirection; </li> <li> 4. For Windows 7 or later, USB 3.0 redirection is recommended. Windows XP system can only enable USB 2.0 redirection </li> </ul>",
    "clientIPTips": "Note: If IP of terminal is within this range at first registration, it will be automatically divided into this classroom",
    "Linux客户端": "Linux Client",
    "虚实双系统断网切换": "Switch virtual desktop to real desktop in case of network interruption",
    "自动切换": "Auto switch",
    "虚系统中断时，倒数": "when virtual system is interrupted, count down",
    "自动进入实系统": "Auto enter real system",
    "一键关机": "One-click shutdown",
    "确定一键关机吗": "Sure to one-click shutdown?",
    "配置系统桌面": "Configure system desktop",
    "同步时间失败": "Synchronize time failed",
    "Europe/Dublin": "Europe/Dublin, Europe/Lisbon, Europe/London",
    "Europe/Paris": "Europe/Paris, Europe/Amsterdam, Europe/Berlin, Europe/Rome, Europe/Stockholm, Europe/Vienna",
    "Asia/Amman": "Asia/Amman, Asia/Beirut, Africa/Cairo, Europe/Athens, Asia/Jerusalem",
    "Asia/Baghdad": "Asia/Baghdad, Europe/Minsk, Asia/Kuwait, Africa/Nairobi",
    "Asia/Muscat": "Asia/Muscat, Asia/Dubai",
    "Asia/Ashkhabad": "Asia/Ashkhabad, Asia/Karachi",
    "Asia/Almaty": "Asia/Almaty, Asia/Dacca, Asia/Bishkek",
    "Asia/Bangkok": "Asia/Bangkok, Asia/Jakarta",
    "Asia/Shanghai": "Asia/Shanghai, Asia/Chongqing, Asia/Hong_Kong, Asia/Singapore, Asia/Taipei",
    "Asia/Tokyo": "Asia/Tokyo, Asia/Seoul, Asia/Yakutsk, Pacific/Palau",
    "Australia/Sydney": "Australia/Sydney, Asia/Vladivostok, Australia/Canberra, Australia/Melbourne, Australia/Queensland",
    "Pacific/Guadalcanal": "Pacific/Guadalcanal, Pacific/Noumea, Asia/Sakhalin",
    "Pacific/Auckland": "Pacific/Auckland, Pacific/Fiji, Pacific/Nauru",
    "Pacific/Tongatapu": "Pacific/Tongatapu, Pacific/Apia",
    "International Date Line West": "International Date Line West",
    "Pacific/Midway": "Pacific/Midway",
    "US/Hawaii": "US/Hawaii, Pacific/Honolulu",
    "US/Alaska": "US/Alaska, Pacific/Gambier",
    "America/Los_Angeles": "America/Los_Angeles, America/Tijuana, America/Vancouver",
    "America/Phoenix": "America/Phoenix, America/Arizona",
    "America/Chicago": "America/Chicago, Chile/EasterIsland, America/Mexico_City, America/Monterrey",
    "America/Indianapolis": "America/Indianapolis, America/Panama, America/Bogota",
    "America/Asuncion": "America/Asuncion, America/La_Paz",
    "Canada/Newfoundland": "Canada/Newfoundland",
    "America/Buenos_Aires": "America/Buenos_Aires, America/Cayenne, America/Sao_Paulo",
    "Atlantic/South_Georgia": "Atlantic/South_Georgia",
    "Atlantic/Azores": "Atlantic/Azores",
    "确定关闭主控节点吗": "Sure to close master node?",
    "同时关闭所有运行的桌面和计算节点": "Close all running desktops and compute nodes",
    "DHCP": "DHCP",
    "当前动态密码": "Current dynamic password",
    "autoTip": "Note: Linux client requires validating password before backup",
    "显卡共享": "GPU sharing",
    "显卡直通": "GPU pass-through",
    "不启用": "Disable",
    "hasGPUTips": "<ul><li>GPU sharing</li><li>Multiple desktops share compute cores of GPU. Maximum number of supported desktops depends on computing power of the GPU.</li> <li>GPU pass-through</li> <li>Pass compute core of GPU through to desktop. Maximum number of desktops supported depends on number of cores in GPU, it is a fixed value.</li></ul> ",
    "使用分布式存储": "Enable distributed storage",
    "distributedStorageTips": "<ul><li>1. Distributed storage can only be used when there is hyper-converged all-in-one machine</li> <li>2. Distributed storage requires extra authorization</li><li>3. Only hyper-converged compute node can be added to distributed storage resource pool </li><li>4. Before adding hyper-converged node, you need to configure distributed storage in advance</li> <li>5. See Distributed Store Deployment Scheme in implementation manual</li></ul>",
    "vdiUserTips": "<ul> <li> 1. It is recommended that you should manually create this account name and password when installing template operating system.</li><li> 2. Even if they are not manually created, guesttools will also automatically change the default account to this account and password </li> <li> 3. When terminal trying to connect with desktop, this account name and password will be used for verification automatically </li> </ul> ",
    "账户名": "Account name",
    "DHCPTips": "<ul><li>1.Terminals in LAN can automatically obtain IP through this DHCP service</li><li>2.DHCP服务的IP段必须与主控节点管理IP在同一网段内</li><li>3.如果要将DHCP服务的IP段修改为其他网段，请先修改主控节点的管理IP，再修改此处</li></ul>",
    "no_gpu_cards": "No GPU card",
    "unsupport_through": "The operating system does not support pass-through",
    "already_through": "GPU in pass-through mode",
    "already_share": "GPU in sharing mode",
    "offline": "Host offline",
    "no_data_network": "No data network",
    "REBUILDING": "rebuilding...",
    "正在更新": "Updating",
    "启用精简配置": "Enable thin provisioning",
    "精简配置": "Thin provisioning",
    "dynamic_lvTips": "<ul><li> 1. When enabled, use storage by thin provisioning </li> <li> 2. You can decide whether to enable it according to if the storage scheme and storage support thin provisioning</li> </ul>",
    "系统设置": "System settings",
    "quickstartTip": "At first landing management platform, you can <span>quickly and conveniently</span> deploy teaching desktop by deploying modules",
    "快速部署": "Rapid deployment",
    "暂不部署": "Do not deploy for now",
    "无限期": "Permanent system license",
    "chromeTips": "There may be compatibility issues with current browser, it is recommended to be replaced with V49 or later chrome browser to optimize user experience",
    "正在设置还原": "Setting up restore",
    "client.connect-type": "Connection mode",
    "重启中状态": "Restarting",
    "USEDIP": "IP has been used",
    "只有未激活状态下的场景才能被删除": "Only scenes that are not activated can be deleted",
    "NOEXSIT_SECNE_TIP": "The scenes does not exist",
    "loginerror": "，The chances you have：{{ 0 }}",
    "maxloginerror": "，You have reached the maximum number of errors, Please try again after 5 minutes",
    "系统审计": "System Audit",
    "开启":"Enable",
    "终端名称/登录序号":"Terminal Name/Login Number：",
    "您的终端序号为":"Your terminal number is：",
    "抢占序号":"This number has been used by other terminals, whether to preempt the number or not?",
    "PERSONAL_TEMP_UPDATE":"All personal desktops associated with this template will be updated, system disk will be rebuilt to the current template state, data disk will remain unchanged, update template or not?",
    "包括":"Include：",
    "PERSONAL_TEMP_UPDATE_TOTAL":"Total desktop number {{1}}",
    "更新中状态":"updating",
    "GPU_THROUGH_TIP":"<ul><li>1. It is only necessary to enable if you need to create a straight desktop based on this template and it will install VGA Drivers successfully after enable。</li><li>2. Be sure to cancel the GPU pass-through of template virtual machine after installed VGA Drivers.</li><ul>",
    "temCopyOrRegisterTip":"<ul><li>1.It is recommended to manually create this account name and password in the template operating system.</li><li>2.If not created manually, guesttools will automatically changes the default account to this account and password.</li><li>3.This account name and password verification are automatically used when the terminal connects to the desktop.</li><ul>",
    "桌面部署帮助":"Desktop deployment help",
    "个人桌面部署流程":"Personal desktop deployment process",
    "教学桌面部署流程":"Teaching desktop deployment process",
    "安装客户端":"Install client",
    "为终端分配教室":"Assign desktops to terminals",
    "分配IP":"Assign IP",
    "终端访问桌面":"Terminal Access Desktop",
    "激活场景":"Activate Scene",
    "加载gesttools":"Loading guesttools",
    "新增模板":"New Template",
    "输入用户名密码":"Enter user name and password",
    "新增用户组":"New User Group",
    "删除用户组":"Delete User Group",
    "组织结构":"Organization structure",
    "自动快照":"Auto snapshot",
    "USB 透传":"USB transparent transmission",
    "个人桌面池":"Personal Desktop Pool",
    "周期":"Cycle",
    "每月":"Monthly",
    "DELETE_AUTO_SNAPSHOT":"Are you sure to delete the automatic snapshot?",
    "每周快照":"Weekly Snapshot",
    "每月快照":"Monthly Snapshot",
    "新增用户":"New User",
    "全部":"All",
    "multiDesktopModeTips": "Support Linux clients and Windows clients to simultaneously connect multiple desktops in the form of windows",
    "bondTips": "<ul> <li> 1. <span style = 'font-weight: bold;'> broadcast </ span>: Broadcast packet through selected network card, The switch will need to set port aggregation and bandwidth will not increase </ li> <br> <li> 2 <round style = 'font-weight: bold;'> roundrobin </ span>: Use polling mode to send packets by network card. The switch needs to set port aggregation and the bandwidth increases </ li> <br> <li> 3. <span style = 'font-weight: bold;'> activebackup </ span>: Only the primary network card sends packets, the backup network card takes over the primary network card when there is fault, The switch does not need to be set, the bandwidth does not increase </ li> <br> <li> 4. <span style = 'font-weight: bold;'> loadbalance </ span>: Select sending network card according to MAC and IP of the data packet , The switch needs to set port aggregation, the bandwidth will increase </ li> <br> <li> 5. <span style = 'font-weight: bold;'> lacp </ span>: Enable LACP active mode to consult with switch, Switch needs to set LACP, the bandwidth will increase </ li> <br> <li> 6. <span style = 'font-weight: bold;'> random </ span>: randomly select network card to send packets, the switch needs to set port Aggregation, brandwith will increase </ li> </ ul> ",
    "/network/manageNetwork": "<ul> <li> 1. The management network is for console node and compute node communication. </ li> <li> </ Li> <br> <li> Image network is for sending image from console node to compute node</ Li> <li> 1. Add management/image network IP in the local network of console node and all compute nodes; ensure all IPs of the new management/image network can be connected. </ Li> <li> 2. Switch to the new management network/image network here </ Li> <li> Note: </ li> <li> 1. The offline computing node can be modified to the new management network IP on the server lock screen. </ Li> <li> li> 2. When modifying image network, only need to modify the image network IP on console node, as long as the compute node is able to communicate with the image network IP on the console node, </ li> </ ul> ",
    "/network/dataNetwork": "<ul> <li> 1. The data network refers to the virtual network used by virtual machine. </li> <li> 2. Creating data network requires associating the distributed virtual switch. </ li > <li> 3 different subnets within the same data network can not be the same network segment, and can not contain or be contained. </li> <br> <li> For example: If subnet 10.16.1.1/16 already exists, neither subnets in the same network segment nor subnets 10.1.1.1/8 and 10.16.1.1/24 can be created under this network. </ Li> < ul> ",
    "/network/virtualSwitch": "<ul> <li> 1. Distributed virtual switches is soft switches created on all hosts. </ li> <li> 2. You need to associate distributed virtual machines in creating data network, one-to-one match in data network and distributed virtual switch. </ Li> <li> 3. After the distributed virtual machine maps the network card on the host, the data network associated with the distributed virtual switch can communicate with the external network. li> </ ul> ",
    "系统服务":"System Services",
    "重启服务":"Restart service",
    "启动服务":"Start Service",
    "确定重启服务吗":"Are you sure to restart the {{1}} service?",
    "确定启动服务吗":"Are you sure to start the {{1}} service?",
    "多桌面模式":"Multi-desktop mode",
    "组件下载":"Component download",
    "组件名称":"Component name",
    "备注":"Remark",
    "安装在windows系统下的客户端":"Client installed on windows",
    "连接模式":"Connection mode",
    "高质量":"High quality",
    "高流畅性":"High fluency",
    "spiceConnectTip": "<ul> <li> 1.High quality: Client takes large bandwidth when connecting to desktop, but have high desktop quality, which is suitable for LAN high bandwidth network environment. </ li> <li> 2. High fluency: Client uses less bandwidth when connecting to desktop, which ensures desktop smoothness, but reduce image quality, which is suitable for the lower bandwidth in public network. </Li> </ul> ",
    "所属资源池/主机":"Affiliated resource pool/Host",
    "桌面类型/透传桌面名":"Desktop type/transparent transmission desktop name",
    "绑定桌面":"Bind desktop",
    "绑定桌面类型":"Bind desktop type",
    "编辑绑定桌面":"Edit binding desktop",
    "资源池/接人主机":"Resource pool/Access host",
    "取消绑定":"Unbind",
    "CANCEL_THROUGH":"Are you sure to unbind desktop?",
    "取消绑定桌面":"Unbind desktop",
    "新增自动快照策略":"New automatic snapshot policy",
    "编辑自动快照策略":"Edit auto snapshot policy",
    "查看自动快照策略":"View auto snapshot policy",
    "删除自动快照策略":"Delete auto snapshot policy",
    "组名":"Group name",
    "所属组":"Affiliated group",
    "修改组名":"Modify group name",
    "USER_TIPGROUP3":"Are you sureto delete the '{{1}}' group?",
    "移动至组":"Move to group",
    "已选中用户":"Selected user",
    "切换到DMS":"Switch to DMS",
    "filterHardTempTips1": "This filter out the hardware templates that meet the following requirements: <br> 1. System disk capacity is larger or equal to the selected personal template system disk <br> 2. The data disk amount needs to be larger or equal to the selected personal template data disk amount <br> 3. Data disk capacity is larger or equal to the capacity of the selected personal template data disk, if there are two data disks, then compare in sequence<br><br>The configuration of the desktop created: <br>1. created personal desktop CPU and memory should be consistent with hardware template<br> 2. create consistent <br> 3. data disk amount and capacity should be consistent with hardware template ",
    "每周1":"Every Monday",
    "每周2":"Every Tuesday",
    "每周3":"Every Wednesday",
    "每周4":"Every Thursday",
    "每周5":"Every Friday",
    "每周6":"Every Saturday",
    "每周7":"Every Sunday",
    "每月1":"On 1st every month",
    "每月2":"On 2ed every month",
    "每月3":"On 3ed every month",
    "每月4":"On 4ed every month",
    "每月5":"On 5ed every month",
    "每月6":"On 6ed every month",
    "每月7":"On 7ed every month",
    "每月8":"On 8ed every month",
    "每月9":"On 9ed every month",
    "每月10":"On 10ed every month",
    "每月11":"On 11th every month",
    "每月12":"On 12th every month",
    "每月13":"On 13th every month",
    "每月14":"On 14th every month",
    "每月15":"On 15th every month",
    "每月16":"On 16th every month",
    "每月17":"On 17th every month",
    "每月18":"On 18th every month",
    "每月19":"On 19th every month",
    "每月20":"On 20th every month",
    "每月21":"On 21th every month",
    "每月22":"On 22th every month",
    "每月23":"On 23th every month",
    "每月24":"On 24th every month",
    "每月25":"On 25th every month",
    "每月26":"On 26th every month",
    "每月27":"On 27th every month",
    "每月28":"On 28th every month",
    "一日":"1st",
    "二日":"2ed",
    "三日":"3rd",
    "四日":"4th",
    "五日":"5th",
    "六日":"6th",
    "七日":"7th",
    "八日":"8th",
    "九日":"9th",
    "十日":"10th",
    "十一日":"11th",
    "十二日":"12th",
    "十三日":"13th",
    "十四日":"14th",
    "十五日":"15th",
    "十六日":"16th",
    "十七日":"17th",
    "十八日":"18th",
    "十九日":"19th",
    "二十日":"20th",
    "二一日":"21th",
    "二二日":"22th",
    "二三日":"23th",
    "二四日":"24th",
    "二五日":"25th",
    "二六日":"26th",
    "二七日":"27th",
    "二八日":"28th",
    "停止":"stop",
    "管理用户关联桌面":"Manage user associated desktops",
    "服务状态异常":"Service status abnormal",
    "用户组/用户/姓名":"User Group/User/Name",
    "关机失败":"Shutdown failed",
    "新增自定义教室":"Add custom classroom",
    "新增自定义模板":"Add custom template",
    "选择组/域/用户":"Select Group/Domain/User",
    "关闭1":"Close",
    "桌面池开机":"Desktop pool boot",
    "桌面池关机":"Desktop pool shutdown",
    "所属用户组":"Affiliated user group",
    "还原属性":"Restore property",
    "修改桌面池":"Modify desktop pool",
    "桌面IP/MAC":"Desktop IP/MAC",
    "选择用户组":"Select user group",
    "从下表中选择一个组":"Select a group from the list below",
    "新增个人桌面池":"New personal desktop pool",
    "桌面池名":"Desktop pool name",
    "未知":"Unknown",
    "其他":"Other",
    "其他状态":"Other status",
    "未知状态":"Unknown state",
    "个人桌面web登录系统":"Ppersonal desktop web login system",
    "LENGTH_LIMIT_POOL":"Names starting with pc plus numbers from {{1}}~{{2}}",
    "SAME_POOL_NAME":"The same personal desktop pool name exists",
    "绑定用户组":"Bind user groups",
    "只能创建两个手动快照":"You can create two manual snapshots",
    "自动挂载共享磁盘":"Automatically mount shared disk",
    "auto_mountPersonalTips": "<ul> <li> Personal Desktop will automatically mount 'public data area', all desktop users can read and write data </ li> <li> 2. personal desktop will be automatically mount 'Private share area', personal desktop users can upload data, other users are read-only</ li> </ ul>",
    "auto_mountTeachTips": "<ul> <li> 1. All desktops will be mounted with 'data sharing area' automatically. All Users can read the information </ li> <li> 2. All the desktops will be automatically mounted with 'Data upload area', users can upload data, can not access other people's information </ li> </ ul>",
    "桌面统计的其中":"，Where",
    "共享磁盘自动清理时间":"Shared disk auto-cleanup time",
    "每":"every",
    "开始自动清理全部文件":"Start clean all files automatically",
    "共享服务":"Shared services",
    "其他桌面":"Other desktop",
    "注册系统桌面":"Register system desktop",
    "USER_TIPGROUP4": "where'{{1}}' ordinary users are associated with other desktops and can not be deleted.",
    "桌面迁移成功": "Desktop migration success",
    "已设置HA": "HA set up",
    "已执行HA": "HA executed",
    "支持扩展屏": "Support extended screen",
    "extendScreenTips": "<ul><li>1. When the terminal connects two monitors, the extended screen take effect.</li><li>2. Only windows client support</li></ul>",
    "LOGIN-COPYRIGHT":"COPYRIGHT:OS-EASY.COM",
    "2~32位字符":"2~32 characters",
    "1~20位字符":"1~20 characters",
    "6~20位字符":"6~20 characters",
    "您没有绑定桌面":"You has not bind the desktop.",
    "服务器或网络出错":"Server or network error",
    "用户名或密码错误":"User name or password error",
    "域用户名或密码错误":"Domain username or password error",
    "用户名格式不对":"User name format is not correct",
    "旧密码格式不对":"The old password is in the wrong format",
    "确认密码格式不对":"Confirm password format is incorrect",
    "两次密码输入不一致":"The two passwords are inconsistent",
    "新密码格式不对":"The new password is in the wrong format",
    "密码修改成功,请重新登录":"Password changed successfully, please login again",
    "网络故障":"Network failure",
    "我已安装完成":"Installed",
    "不同网卡上不能存在相同网段的IP":"The IP of the same network segment cannot exist on different network cards",
    "migrationTip":"The target host's CPU series need to higher than the original host machine",
    "terminalSetTips": "<ul><li>1. All tab page parameters will take effect</li><li>2. After modifying the parameters, the terminal will be automatically restarte and take effect</li></ul>",
    "开机中":"Rebooting",
    "关机中":"Shutting Down",
    "此处筛选出不还原的个人桌面":"Description: here we screen the unrestored personal desktop",
    "multifyNetsTips":"Please enter the operating system to manually fill out all the IP after setting",
    "安装完成确认":"Complete installation confirmation",
    "我已安装完成确认":"After the installation is complete, the system desktop will be turned off.Make sure that this is done after the installation is complete,confirm the installation is complete?",
    "HA_SAME_NAME_TIP":"The same desktop HA policy name exists",
    "无可用教学桌面":"Unavailable teaching desktop",
    "VDI_AlarmPlicy_TIPS":"The same alarm policy name exists",
    "LENGTH_LIMIT_WORD":"Support 1 to 15 character lengths",
    "LENGTH_LIMIT_WORD_TITLE":"The English, minus numbers or characters, does not support the pure digital",
    "SCHEDUL_SAME_NAME_TIPS":"The same planned task name exists"
}
