{
	"网络已断开": "Network disconnected, connect to the server failed",
	"确定退出客户端吗:": "Are you sure to exit the client ?",
	"退出": "Exit",
	"删除角色": "Delete role",
	"OEM_UPGRADE_MESS": "Detect new resource，the client will automatically restart after update is finished, please wait...",
	"UPGRADE_MESS_WINDOWS": "Updates are detected, the computer will automatically reboot after upgrade, upgrade immediately ?",
	"关闭终端同时关闭桌面": "Close desktop while closing terminal",
	"关闭桌面同时关闭终端": "Close terminal while closing desktop",
	"个人桌面关机": "Personal desktop shutdown mode",
	"教学桌面关机": "Teaching desktop shutdown mode",
	"开机自启": "Startup in booting",
	"全屏可退出": "Able to exit full screen",
	"窗口模式": "Window Mode",
	"当前版本号": "Current Version",
	"终端名称": "Terminal Name",
	"未升级组件详情": "Not upgraded component details",
	"升级": "Upgrade",
	"教室/所有人": "Classroom/Owner",
	"正在连接服务器": "connecting server...",
	"所有": "All",
	"数据盘清除": "Data disk clear",
	"系统盘还原": "System disk restore",
	"最佳分辨率": "Best resolution",
	"最佳": "Best",
	"t-8": "REGISTER_TEMPLATE",
	"教室重复": "The IP range is the same with classroom XXX,please fill in again",
	"有线": "Wired",
	"REGISTER_FAILED": "Register failed",
	"自动进入场景": "Will auto log in",
	"新密码与旧密码相同": "The new password is the same with the old",
	"WEBSITE_init": "www.os-easy.com",
	"WEBSITE_login": "WWW.OS-EASY.COM",
	"WEBSITE_login_a": "http://www.os-easy.com",
	"2UPGRADEMESS": "Please ensure the client is running and successfully connect to the server,the client will reboot after upgrade,confirm to upgrade now ?",
	"UPGRADE_MESS_2": "System is upgrading, please do not shut off the power, the system will automatically restart after a successful upgrade",
	"UPGRADE_MESS_1": "Detected a new version, whether to upgrade immediately?",
	"重试": "retry",
	"不支持": "Unsupported",
	"UPGRADEMESS": "After upgraded, you need to restart the server to take effect,  upgrade immediately?",
	"查看未升级组件详情": "Not upgraded component details",
	"立即升级": "Upgrade Now",
	"已升级组件数/组件总数": "Upgrade components/Total components",
	"已连接": "Connected",
	"正在连接": "Connecting",
	"无线": "Wifi",
	"所有教室": "All",
	"REGESTER": "Registering...",
	"终端结束IP": "Default terminal end IP",
	"终端起始IP": "Default terminal start IP",
	"终端IP范围": "Default terminal IP range",
	"桌面IP段": "Desktop IP range",
	"系统包": "System package",
	"选择类型": "Select type",
	"软件包": "Software package",
	"无可注册模板": "No template to register",
	"模板注册": "Register Template",
	"注册": "Register Template",
	"虚拟机自助": "Virtual machine self service",
	"重启确认": "Reboot template",
	"不能超过50位字符": "Not more than 50 characters",
	"系统获取": "System Gain",
	"静态IP": "Stastic IP",
	"网络连接": "Network",
	"不是一个可接受的文件类型": "Is not an accepted file type",
	"文件为空": "Is empty",
	"超出文件大小限制": "Exceeded file size limit",
	"重启服务器生效": "Restart the server to take effect after modified",
	"AUTHROIZE_USER_TIP": "Please authorize administrator",
	"授权管理用户": "Authorize Administrator",
	"UPDATE_TEMPLATE_TIP": "Close the edit window directly, can temporarily not update the template, and save your updated content",
	"UPDATE_TEMPLATE": "The virtual machine will be closed,confirm to update template?",
	"角色管理": "Role manage",
	"管理范围": "Management scope",
	"权限分配": "Permission distribution",
	"编辑角色": "Edit role",
	"新增角色": "Add role",
	"修改时间": "Modification time",
	"修改人": "Modifier",
	"授权管理员数": "Authorized number",
	"角色名": "Role name",
	"角色": "Role",
	"优先启用HA服务器": "Priority to enable HA server",
	"启用全局HA": "Enable global HA",
	"选择日期": "Select a date",
	"选择周几": "Select a week",
	"不存在HA服务器": "There is no HA server",
	"请选择HA服务器": "Please select a server to HA",
	"启用HA": "Enable HA",
	"POOL_TIP": "Please select a management scope",
	"ROEL_TIP": "The role binded with administrator, unable to delete",
	"DELETE_ROLES2": "'{{1}}' associated with administrators and can not be deleted",
	"DELETE_ROLES1": "Confirm to delete '{{1}}' ?",
	"PERMISSION_TIP": "Please select a permission",
	"vdiTerminalconfigureName_TIP": "Can not modify name under off state in the selected terminals",
	"新增域": "Add Domain",
	"持续开机时间": "Running Time",
	"FORMAT": "Format",
	"ping包数": "Ping packets",
	"开始更新": "Start update",
	"SYSTEMUPDATE3": "System is upgrading, please do not turn the power off or remove the usb flash drive, system will automatically restart after a successful upgrade",
	"SYSTEMUPDATE2": "Upgrade file not detected, please update again",
	"空间不够": "Out of disk space",
	"SYSTEMUPDATE1": "Please insert the upgrade usb, click update to start the update",
	"重新配置序列号": "< Reconfigure the serial number",
	"序列号配置成功": "Configuration is successful, your serial number is",
	"手动输入": "Custom",
	"序列号自动加1": "Auto adding one",
	"终端排序": "Terminal sorting",
	"RETRY": "Retry",
	"TIMEOUT": "Timeout",
	"同步完成": "Complete",
	"TERMINAL_FAIL_TIP": "The request for terminal timeout!",
	"不可编辑": "IP is being used，unable to edit",
	"确定重启吗": "Confirm to restart?",
	"确定关机吗": "Confirm to shutdown?",
	"注销自动登录用户": "Log off automatically logged",
	"CPU信息": "CPU",
	"内存容量": "Memory capacity",
	"硬盘容量": "Hard disk capacity",
	"版本号": "version",
	"产品名称": "Product Name",
	"桌面属性": "desktop property",
	"系统属性": "system property",
	"获取": "obtain",
	"正在获取": "accessing..",
	"手动配置": "manual configuration",
	"个人桌面登录": "Personal desktop login",
	"请选择教学桌面": "Please select teaching desktop",
	"自动进入桌面": "Will auto log in",
	"请选择个人桌面": "Please select personal desktop",
	"用户名或密码不能为空": "The user name or password cannot be empty",
	"密码修改成功": "Password update successful, please log in again",
	"格式不正确": "Incorrect format, please reenter",
	"两次输入密码不一致": "Entered passwords differ,please reenter",
	"连接超时": "Timeout,please retry",
	"注销失败": "Logoff failed",
	"注销成功": "Logoff  successful",
	"请输入1024-65535之间的端口号": "The port number show between 1024-65535",
	"输入序号需大于起始序号": "The number should be equal or greater than the starting number",
	"请检查网络配置": "Failed to connect server，please check  your network config",
	"连接服务器失败": "Failed to connect server",
	"保存失败": "Save failure",
	"保存成功": "Save successful",
	"密码错误": "Password is error",
	"COPYRIGTH": "COPYRIGHT:OS-EASY.COM",
	"SETTERMINAL_TIP": "Note: Please restart the terminal after the modification of parameter setting",
	"ABOUT_NAME": "噢易云计算教育桌面云软件",
	"h-3": "CHECK_MEMORY",
	"h-2": "CHECK_KVM_SUPPORT",
	"h-1": "CHANGE_HOST_IP",
	"s-3": "SNAPSHOT_DELETE",
	"s-2": "SNAPSHOT_TAKE",
	"s-1": "SNAPSHOT_RESTORE",
	"t-7": "SYNC_TEMPLATE",
	"t-6": "CLONE_TEMPLATE",
	"t-5": "INSTALL_COMPLETE",
	"t-4": "CREATE_TEMPLATE",
	"t-3": "DELETE_IMAGE",
	"t-2": "UPDATE_TEMPLATE",
	"t-1": "UPDATE_MODE_INSTANCE",
	"i-19": "RESET_MODE_VM",
	"i-18": "LIVE_MIGRATION",
	"i-17": "DISABLE_USBREDIR",
	"i-16": "ENABLE_USBREDIR",
	"i-15": "DISABLE_ROLLBACK",
	"i-14": "ENABLE_ROLLBACK",
	"i-13": "CHANGE_INSTANCE_IP",
	"i-12": "CHANGE_MEDIA",
	"i-11": "DESTORY_VM",
	"i-10": "RESIZE_DISK",
	"i-9": "HIBERNATE",
	"i-8": "UNPAUSE",
	"i-7": "PAUSE",
	"i-6": "CREATE_VM",
	"i-5": "REBOOT_VM",
	"i-4": "RESIZE",
	"i-3": "SAVE_TEMPLATE_VM",
	"i-2": "SHUTDOWN_VM",
	"i-1": "START_VM",
	"REPAIR": "Repair",
	"速度": "Speed",
	"UPLOADING": "Uploading...",
	"模板分布": "Template distribution",
	"SET_RESOLUTION": "System will restart automatically and save the settings, confirm to save?",
	"NOWEEK": "Not yet arrange class time, please arrange class time first!",
	"OUTOFFSCHULE": "The current time not in the class time!",
	"进度": "Progress",
	"设置分辨率": "Set the resolution",
	"登录终端名/IP": "Terminal name/IP",
	"持续运行时间": "Running Time",
	"禁用启用": "Disable/Enable",
	"调整范围": "Amend",
	"MAKING_SEED": "Making seed...",
	"使用NTP": "Use NTP",
	"城市": "City",
	"区域": "District",
	"麦克风": "Microphone",
	"音量": "Volume",
	"导出日志": "Export Log",
	"系统更新": "Update System",
	"重启系统": "Reboot System",
	"声音": "Voice",
	"属性": "Attribute",
	"持续发送ping包": "Continue to send ping packets",
	"尝试修复": "Try to repair",
	"地址": "Address",
	"字节长度": "Byte Size",
	"IP地址": "IP Address",
	"静态配置": "Static Configuration",
	"配置": "Configure",
	"网络诊断": "Network Diagnosis",
	"网络设置": "Network Settings",
	"端口": "Port",
	"旧密码": "Old Password",
	"修改密码": "Change Password",
	"保存密码": "Save Password",
	"每次不还原": "Every time not restore",
	"每次还原": "Every time restore",
	"返回信息格式错误": "Return error message format",
	"新建失败": "error",
	"TEMP_SYNC_FAILED": "Sync failed",
	"TEMPLATE_SYNC_FAILED": "Send failed",
	"正在生成种子文件": "Making seed",
	"SYNC_INFOR": "Template \"{{1}}\" distribution info",
	"登录时间": "( login 5 seconds at least,not more than 9999 seconds)",
	"TITLE_NAME": "OS-EASY",
	"/user/domain/:id": "<ul><li> domain server to open the state, the user can perform the synchronization domain user operation. </li><li> default synchronization of the default synchronization domain user directory data. </li></ul>",
	"/user/domain": "<ul><li>The domain server IP must communicate with the management server IP, domain name and domain server IP match, and can perform the new domain operation.</li></ul>",
	"GOD_VERSION": "dev",
	"查看同步信息": "View synchronization information",
	"-1": "All type",
	"正在作种": "Seeding",
	"正在下载": "Downloading",
	"外网IP": "Outer net ip",
	"NET": "Network",
	"networkTitle": "Network{{1}}",
	"等考模式": "RDP",
	"ip分配": "Ip assignment",
	"优先级": "Priority",
	"节点IP": "Node IP",
	"版本": "Version",
	"节点名称": "Node name",
	"0xFF": "Vendor Specific",
	"0xFE": "Application Specific",
	"0xEF": "Miscellaneous",
	"0xE0": "Wireless Controller",
	"0xDC": "Diagnostic Device",
	"0x11": "Billboard Device Class",
	"0x10": "Audio/Video Devices",
	"0x0F": "Personal Healthcare",
	"0x0E": "Video",
	"0x0D": "Content Security",
	"0x0B": "Smart Card",
	"0x0A": "CDC-Data",
	"0x09": "Hub",
	"0x08": "Mass Storage",
	"0x07": "Printer",
	"0x06": "Image",
	"0x05": "Physical",
	"0x03": "HID (Human Interface Device)",
	"0x02": "Communications and CDC Control",
	"0x01": "Audio",
	"0x00": "Use class information in the Interface Descriptors",
	"RULE_NAME": "Rule name",
	"API_CODE": "Error code :",
	"HOST_NAME_IS_NOT": "The host name is invalid",
	"USER_NAME_IS_NOT": "The user name is invalid",
	"扩容大小": "Increase size",
	"扩容模板C盘": "Expansion disk C",
	"TEMP_UNDO_TIP": "The template will be returned to the last time state, confirm to restore?",
	"撤销本次": "Undo",
	"TEMP_SAVE_TIP": "Please make sure the current template can be normal use,confirm to to save?",
	"PREFIX001": "Prefix + three-digit number",
	"PREFIX01": "Prefix + two-digit number",
	"PREFIX1": "Prefix + one-digit number",
	"PREFIX": "Prefix",
	"USERNAME_SAMETO_TEMPLATE": "The user name is the same with the template",
	"USER_NAME_IS_": "Preview:the user name is {{1}}",
	"DEFAULT": "default",
	"CONFIGURE_USER_NAME": "Configure user name",
	"ADVANCED": "advanced",
	"HOST_NAME_IS_": "Preview：the host name is {{1}}",
	"BEGIN_WITH": "Begin with number",
	"TYPE": "Type",
	"HSOT_NAME_CONFIG": "Configure host name",
	"使用配置": "configure RDP",
	"自由分配": "Auto",
	"CLASSROOM": "Classroom(network)",
	"编辑USB重定向": "Edit USB redirect",
	"TEMPLATE_CLONING": "Cloning...",
	"DELE_USB_TIP": "Confirm to delete the USB redirects?",
	"DELE_USB": "Delete USB redirect",
	"新增USB重定向": "Add USB redirect",
	"VID": "VID",
	"PID": "PID",
	"id": "ID",
	"WRONG_NAME": "Template name exists!",
	"vdiTerminalconfigure_TIP": "Can not set operating parameters under off state in the selected terminals",
	"TEM_UNDOSYNC": "Template will return to the last updated desktop status, Confirm to undo the last update?",
	"COPY_TEM": "Save template as",
	"MORE": "more",
	"UNDO_SYNC_TEM": "Undo the last update",
	"SUMMARY_HOST_DESC": "Total {{1}} , <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown\"></span> {{3}}",
	"SUMMARY_TITLE_NODE": "<span><em class='en en-t'> compute node </em> <em class='en en-n'><strong> {{1}} </strong></em></span>",
	"SUMMARY_TITLE_DESKTOP": "<span><em class='en en-t'> teaching desktop </em> <em class='en en-n'><strong> {{1}} </strong> </em></span> <span><em class='en en-t'> personal desktop </em> <em class='en en-n'><strong> {{2}} </strong> </em></span>",
	"SUMMARY_TITLE_CLIENT": "<span><em class='en en-t'> classroom </em> <em class='en en-n'><strong> {{1}} </strong> </em></span> <span><em class='en en-t'> terminal </em> <em class='en en-n'><strong> {{2}} </strong> </em></span>",
	"SUMMARY_DESKTOP_DESC": "Total {{1}} , <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown\"> </span> {{3}}",
	"SUMMARY_CLIENT_DESC": "Total {{1}} , <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown\"></span> {{3}}",
	"SUMMARY_ALL_CORE": "Total {{1}} physical core(s)",
	"SUMMARY_VCPU_CORE": "{{1}} virtual core(s) running",
	"SUMMARY_VCPU_TOTAL": "Total  <strong> {{1}} </strong> virtual core(s)",
	"SUMMARY_SIZE_TOTAL": "Total <strong> {{1}} </strong> GB",
	"SUMMARY_SIZE_USED": "{{1}} GB used",
	"SUMMARY_SIZE_FREE": "{{1}} GB available",
	"HOST_TOTAL_MESS": "{{1}} host(s), <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown\"> </span> {{3}}",
	"HOST": "Host",
	"查看桌面": "View desktop",
	"桌面修改": "Modify desktop",
	"存为模板": "Save as template",
	"桌面强制关机": "Forcefully shutdown desktop",
	"桌面自然关机": "Naturally shutdown desktop",
	"确定强制关闭桌面吗": "Confirm to shut down the desktop forcefully ?",
	"桌面重启": "Restart desktop",
	"桌面暂停": "Pause desktop",
	"桌面恢复": "Recover desktop",
	"桌面删除": "Delete desktop",
	"桌面删除后无法恢复，确定删除桌面吗": "Unable to restore the desktop after you deleted, confirm to delete the desktop?",
	"确定恢复桌面吗": "Confirm to restore the desktop?",
	"确定暂停桌面吗": "Confirm to pause the desktop?",
	"确定重启桌面吗": "Confirm to restart the desktop?",
	"确定自然关闭桌面吗": "Confirm to shut down the desktop naturally?",
	"确定强制关闭场景吗": "Confirm to shut down the scene forcefully ?",
	"确定自然关闭场景吗": "Confirm to shut down the scene naturally?",
	"删除场景": "Deleted scenes",
	"删除场景无法恢复，确定删除场景吗": "Deleted scenes can not be recovered, confirm to delete scenes?",
	"存在未关机的桌面,仍然删除场景吗": "There is desktop in running state , confirm to delete the scene?",
	"主控节点": "Consoles",
	"计算节点": "Computing nodes",
	"教室": "Classroom",
	"终端": "Terminal",
	"概要": "Summary",
	"资源池": "Resource",
	"主机管理": "Host",
	"网络管理": "Network",
	"存储管理": "Storage",
	"桌面": "Desktop",
	"教学桌面": "Teaching desktop",
	"个人桌面": "Personal desktop",
	"模板": "Template",
	"教学模板": "Teaching template",
	"个人模板": "Personal template",
	"硬件模板": "Hardware template",
	"教室管理": "Classroom",
	"终端管理": "Terminal",
	"会话管理": "Session",
	"用户": "User",
	"管理用户": "Administrator",
	"普通用户": "Common user",
	"监控": "Monitor",
	"主机监控": "Host monitoring",
	"桌面监控": "Desktop monitoring",
	"告警信息": "Alarm information",
	"排课": "Timetable",
	"课程列表": "Course list",
	"系统": "System",
	"系统备份": "System backup",
	"系统 ISO": "Package",
	"系统升级": "System upgrade",
	"操作日志": "Operation log",
	"关于": "About",
	"帮助": "Help",
	"所有服务器": "All servers",
	"选择服务器": "Select server:",
	"新增": "Add",
	"编辑": "Edit",
	"删除": "Delete",
	"提交": "Submit",
	"重置": "Reset",
	"自定义": "Custom",
	"系统登录名生成策略": "Login named by",
	"完成": "Finish",
	"基本信息": "Basic Info",
	"虚拟硬件信息": "Virtual hardware information",
	"等考配置": "Configure RDP",
	"配置虚拟硬件": "Configure virtual hardware",
	"绑定用户": "Bind user",
	"下载日志": "download logs",
	"下载": "Download",
	"LOADING_TEXT": "Data is loading ...",
	"NO_MATCHING_DATA": "No matching data",
	"TEMPLATE_UPDATE_FAILED": "Update failed",
	"TEMPLATE_UPDATING": "Updating ...",
	"MAKING": "Installing ...",
	"BUILDING": "On creating...",
	"SYNCING": "Syncing ...",
	"已用/总大小": "used/total",
	"关联桌面数": "Associated desktop",
	"创建者": "Creator",
	"创建时间": "Create time",
	"新增教学模板": "Add teaching template",
	"新增个人模板": "Add personal template",
	"模板名": "Template name",
	"LENGTH_LIMIT": "{{1}} ~ {{2}} characters",
	"不能超过30位字符": "Not more than 30 characters",
	"1~5位数字": "1 ~ 3 digits",
	"2~20位英文和数字": "2 ~ 20 letters or digits",
	"请输入搜索内容": "Please input search content",
	"备份名为英文或数字": "Backup name must be letters or digits",
	"请输入模板名": "Please input template name",
	"请先选择宿主机": "Please select host first",
	"所有人": "Owner",
	"选择模板": "Select template",
	"处理器": "Processor",
	"内存": "Memory",
	"系统盘/数据盘": "System disk/data disk",
	"安装方式": "Install way",
	"自动安装": "Auto-install",
	"手动安装": "Manual installation",
	"AUTO_INSTALL_TIP": "Configure the correct secret key, user information, template in advance, the  template operating system will be automatically installed, suitable for unattended operation.",
	"MANUAL_INSTALL_TIP": "After the configuration wizard finished, you should install the OS in template, need to manually configure the secret key, user information during the installation, suit for unattended operation.",
	"选择ISO": "Select package",
	"配置系统详情": "Configure system info",
	"windows产品秘钥": "Windows product secret key",
	"要装的windows版本": "System version",
	"用户名": "User name",
	"密码": "Password",
	"COMPLETE_INFOR": "Congratulations, the basic information of the template has been configured successfully, click \"Finish\" button to start installing template",
	"确定": "OK",
	"取消": "Cancel",
	"更新桌面": "Update desktop",
	"UPDATE_DESKTOP_INFOR": "The following scenes will be updated, please check if all the associated desktops are shut down. (Note: update desktop will turn off the desktop and the corresponding scene, please manually turn on after the update finished)",
	"CPU": "CPU",
	"系统盘": "System disk",
	"数据盘": "Data disk",
	"新增硬件模板": "Add hardware template",
	"名称": "Name",
	"增加数据盘": "Increase data disk",
	"移除数据盘": "Remove data disk",
	"教室名称": "Classroom name",
	"当前终端数": "Terminal amount",
	"当前场景数": "Scene amount",
	"网络": "Network",
	"操作": "Operate",
	"编辑教室": "Edit classroom",
	"新增教室": "Add classroom",
	"分配教室": "Assign classroom",
	"排序": "Sort",
	"人工排序": "Sort manually",
	"自动排序": "Sort automatically",
	"设置终端": "Terminal setting",
	"修改终端名": "Modify name",
	"设置运行参数": "Parameter setting",
	"固定桌面IP": "Bind desktop IP",
	"唤醒": "Wake up",
	"关机": "Shutdown",
	"中断会话": "Terminate session",
	"终端名": "Terminal name",
	"登录序号": "Login sequence",
	"终端IP/MAC": "Terminal IP/MAC",
	"运行状态": "Status",
	"接入桌面": "Accessed desktop",
	"接入终端": "Accessed terminal",
	"接入时间": "Access time",
	"接入时长": "Connection time",
	"终端列表": "Terminal list",
	"开始排序": "Start sorting",
	"起始序号": "Start NO.",
	"完成排序": "Complete sorting",
	"模式": "Mode",
	"权限": "Strategy",
	"快捷键": "Shortcut",
	"个性化": "Personalization",
	"默认模式选择": "Default selection",
	"混合模式": "Mixed mode",
	"教学模式": "Teaching mode",
	"个人模式": "Personal mode",
	"自动登录": "Automatic login",
	"启用": "Enable",
	"秒": "Second",
	"Windows客户端": "Windows client operation mode",
	"开机启动": "Boot",
	"全屏不可退出": "Unable to exit full screen",
	"隐藏退出按钮": "Hide the exit button",
	"关闭桌面即关闭终端": "Close desktop that is to close terminal",
	"WINDOWS_SHOUCUTS_DESCRIBE": "Exit client",
	"LINUX_SHOUCUTS_DESCRIBE": "Client connect desktop by full-screen, making it presents a window",
	"分辨率": "Terminal Resolution",
	"服务器IP": "Server IP",
	"动态密码": "Dynamic password",
	"超级密码": "Terminal password",
	"开始IP": "IP starts from",
	"终端名前缀": "Prefix of terminal name",
	"登录名": "User name",
	"姓名": "Full name",
	"电子邮箱": "Email",
	"联系电话": "Telephone",
	"上次登录IP": "Latest login IP",
	"导出": "Export",
	"新增管理用户": "Add administrator",
	"新增普通用户": "Add common user",
	"性别": "Sex",
	"男": "Male",
	"女": "Female",
	"类型": "Type",
	"管理员": "Administrator",
	"编辑管理用户": "Edit administrator",
	"编辑普通用户": "Edit common user",
	"教师": "Teacher",
	"CPU占用率": "CPU utilization rate",
	"网络上下行流量": "Upload/Download dataflow",
	"磁盘读写速度": "I/O speed",
	"进程": "Process",
	"桌面名称": "Desktop name",
	"桌面编号": "Desktop numbers",
	"桌面类型": "Desktop type",
	"状态：": "State: ",
	"清空": "Empty",
	"编号": "No.",
	"内容": "Description",
	"确认密码": "Confirm password",
	"新密码": "New password",
	"存储": "Storage",
	"时间": "Time",
	"重启": "Restart",
	"关闭": "Shutdown",
	"恢复": "Recover",
	"高级": "Advance",
	"DESKTOP": "Desktop",
	"桥接": "Bridge",
	"IP范围": "IP range",
	"子网掩码": "Subnet mask",
	"网关": "Gateway",
	"是": "YES",
	"否": "NO",
	"主机": "Host",
	"主机：": "Host : ",
	"刷新频率": "Refresh rate:",
	"用途": "Partition",
	"存储名": "Storage name",
	"存储服务器": "Storage server",
	"位置": "Location",
	"容量": "Size",
	"可用空间": "Available",
	"状态": "Status",
	"缓存区": "Buffer",
	"数据区": "Data partition",
	"系统区": "System partition",
	"正常": "Normal",
	"异常": "Abnormal",
	"准备中": "Preparing",
	"本地磁盘": "Local disk",
	"iscsi 磁盘": "iscsi disk",
	"网络文件系统": "Network file system",
	"FC 光纤存储": "FC optical storage",
	"高級管理": "Advance management",
	"服务": "Service",
	"root密码": "root password",
	"桌面设置": "Desktop setting",
	"服务名称": "Service name",
	"描述": "Description",
	"开关": "Operate",
	"日志": "Log",
	"场景桌面开机": "Boot",
	"场景桌面关机": "Shutdown",
	"强制关机": "Forcefully shutdown",
	"自然关机": "Naturally shutdown",
	"场景名": "name",
	"所属教室": "Classroom",
	"激活": "Activate",
	"在线/桌面数": "Online / Total",
	"桌面模板": "Desktop template",
	"还原设置": "Restore type",
	"每次都还原": "Every time",
	"按周还原": "Per week",
	"按月还原": "Per month",
	"无还原设置": "Never",
	"开机": "Boot",
	"暂停": "Pause",
	"桌面名": "Desktop name",
	"OS/模板": "OS / template",
	"CPU/内存/数据盘": "CPU / memory / data disk",
	"宿主机": "Physical host",
	"开机状态": "On",
	"关机状态": "Off",
	"挂起状态": "Pending",
	"迁移状态": "Migration",
	"全部状态": "All",
	"创建中状态": "Creating",
	"错误状态": "Error",
	"异常状态": "Abnormal",
	"未知异常状态": "Unknown exception",
	"操作系统": "OS",
	"模板名称": "Template name",
	"返回": "Back",
	"系统登录名": "System login",
	"已分配": "Assigned",
	"分配对象": "Assign to",
	"已使用": "Used",
	"使用对象": "Used by",
	"说明": "Description",
	"类型-网关": "Gateway",
	"类型-桌面": "Desktop",
	"备份": "Backup",
	"备份文件名": "Backup file name",
	"大小": "Size",
	"备份时间": "Backup Time",
	"ISO名": "ISO name",
	"系统类型": "System type",
	"上传时间": "Upload time",
	"KEY_PATTERN": "Such as: 87VT2-FY2XW-F7K39-W3T8R-XMFGF",
	"支持": "Support",
	"Windows 7 系列": "Windows 7 Series",
	"当前版本": "The current version",
	"升级包": "Upgrade package",
	"操作者": "Operator",
	"操作内容": "Operation log",
	"操作时间": "Operation time",
	"网卡名称": "NIC name",
	"MAC地址": "MAC",
	"网卡": "NIC type",
	"网卡IP": "NIC IP",
	"默认网关": "Gateway",
	"管理台": "Console",
	"保存": "Save",
	"恢复主机": "Recover host",
	"选择主机IP": "Select host IP",
	"新增IP": "Add IP",
	"结束IP": "IP ends to",
	"新增存储": "Add storage",
	"存储类型": "Storage type",
	"所在服务器": "Local server",
	"路径": "Path",
	"存储服务器挂载路径": "Storage server mounting path",
	"搜索": "Search",
	"新建逻辑卷": "Create logical volume",
	"使用": "Use",
	"逻辑卷": "Logical volume",
	"使用者": "User",
	"修改桌面": "Modify the desktop",
	"关联用户": "Associated user",
	"设置静态IP": "Set static IP",
	"不分配": "Not allocated",
	"动态迁移": "Dynamic migration",
	"选择迁移主机": "Select host",
	"新增个人桌面": "Add personal desktop",
	"桌面数": "Desktop amount",
	"系统自动选择合适数量的IP给虚拟机": "----System  selects the appropriate amount of IP to virtual machine automatically",
	"起始IP": "Begin IP",
	"请选择一个个人桌面模板类型：": "Please select a personal template",
	"其它": "Other",
	"绑定规则": "Rule",
	"完全匹配": "Exactly match",
	"循环匹配": "Circularly match",
	"选择用户": "User",
	"从下表选择一个或多个用户": "Select (one or more)",
	"已选择用户": "Selected",
	"选择系统类型": "Select the system type",
	"分类": "System type",
	"模板类型": "Template type",
	"快照管理": "Snapshot management",
	"快照名": "Snapshot name",
	"快照描述": "Snapshot description",
	"新增快照": "Add snapshot",
	"新增教学场景": "Add teaching scene",
	"指定到教室": "Classroom",
	"请选择一个教学桌面模板类型：": "Please select a teaching desktop template type:",
	"周一": "Mon",
	"周二": "Tue",
	"周三": "Wed",
	"周四": "Thu",
	"周五": "Fri",
	"周六": "Sat",
	"周日": "Sun",
	"每月第几天": "The day",
	"USB使用": "Enable USB",
	"计算机名生成策略": "PC named by",
	"自定义规则": "Custom rules",
	"系统默认规则": "System default rules",
	"计算机名规则": "Rule",
	"系统登录名规则": "Rule",
	"修改场景": "Modify scene",
	"MESS_REBOOT": "Restart computer to take effect after the network modified!",
	"MESS_SAVEROOT": "root password:",
	"MESS_ROOTNEED": "Need to verify root password when enable services and download log etc advanced feature!",
	"MESS_MAXINSTANCE": "Maximum running desktop amount",
	"MESS_NORESTOREIP": "No recoverable host IP!",
	"MESS_NEWSTORAGE": "4-20  digits or letters",
	"MESS_DYNAMIC": "Does not exist migratory hosts!",
	"MESS_NEWPERSON1": "1. Default is not bound IP & nbsp; & nbsp;. 2 After successfully created, through the personal desktop -> desktop to modify reassign fixed IP",
	"MESS_NEWPERSON2": "----System will assign same amount IP(start IP from setting) in network pool to match virtual machine",
	"MESS_NEWPERSON3": "---- The amount of selected users must be equal to created desktops, a user corresponds to one desktop",
	"MESS_NEWPERSON4": "---- The amount of selected users must be less than or equal to  created desktops, a user corresponds to one or multiple desktops",
	"MESS_SNAPSHOT": "1. Snapshot does not support usb redirection",
	"MESS_SNAPSHOT2": "2.Able to add new snapshot only when the desktop is in running state",
	"MESS_SENCEALTER": "Only can modify this after the desktop closed",
	"硬件配置": "Configure hardware",
	"核": "core",
	"1~8核": "1 ~ 8 Core",
	"1核": "1 Core",
	"2核": "2 Core",
	"4核": "4 Core",
	"8核": "8 Core",
	"选择教室": "Select classroom:",
	"显示": "Show",
	"每排显示": "Each row show",
	"CLIENT_REQUSET": "Sending request ...",
	"可进入排序": "Available sort amount",
	"TEMPLATE_DESC": "<span class = \"totalmess\"> <strong> {{1}} </strong> template(s) ,  <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown \"> </span> {{3}} </span>",
	"CLIENT_DESC": "<strong> {{1}} </strong> terminal(s) , <span class = \"status16 running\" > </span> {{2}} , <span class=\"status16 shutdown\"></span> {{3}}",
	"CLIENTSORT_DESC": "Client {{1}} , <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown\" > </span> {{3}} ,",
	"编辑模板": "Edit template",
	"该模版未关联任何场景": "The template is not related to any scene",
	"下载模版": "Download template",
	"TEMPLATE_DELETE_TIP": "The template associated with other desktop, firstly delete these desktops",
	"删除模版": "Delete template",
	"CLIENT_TIP1": "Can not modify terminal name under off state",
	"CLIENT_TIP2": "Can not set operating parameters under off state",
	"CLIENT_TIP3": "Terminal has been waked up",
	"CLIENT_TIP4": "Terminal has been shut down",
	"CLIENT_TIP5": "Can not interrupt the session under off state",
	"CLIENT_TIP6": "Can not be deleted under boot state",
	"加载ISO": "Load package",
	"发送": "Send",
	"更新模板": "Update template",
	"保存模板": "Save template",
	"删除硬件模板": "Delete hardware template",
	"删除教学模板": "Delete teaching template",
	"删除个人模板": "Remove personal template",
	"NODELETE_TEACH_TEMPLATE": "'{{1}}' associated with other desktop and can not be deleted",
	"唤醒确认": "Wake up terminal",
	"CLIENT_TIPGROUP1": "Confirm to wake up '{{1}}' ?",
	"CLIENT_TIPGROUP2": "Confirm to close '{{1}}' ?",
	"CLIENT_TIPGROUP3": "Confirm to terminate '{{1}}' ?",
	"CLIENT_TIPGROUP4": "Confirm to delete '{{1}}' ?",
	"删除教室": "Delete classroom",
	"CLASSROOM_TIPGROUP1": "Confirm to delete '{{1}}' ?",
	"CLASSROOM_TIPGROUP2": "'{{1}}' associated scenarios or other terminals, cannot be deleted",
	"SESSION_TIPGROUP1": "Confirm to terminate the session?",
	"删除用户": "Delete user",
	"USER_TIPGROUP1": "Confirm to delete '{{1}}' ?",
	"ALARM_DELETE": "Confirm to delete?",
	"清空确认": "Empty alarm",
	"CLEAR_TIP": "Confirm to empty alarm information ?",
	"上一步": "Previous",
	"下一步": "Next",
	"PAGE": "Show {{1}} ~ {{2}}, total {{3}}",
	"退出系统": "Exit",
	"课时设置": "Class arrangement",
	"全选": "Select all",
	"单周": "Odd week(s)",
	"双周": "Dual week(s)",
	"清除全部课表": "Clear all courses",
	"保存修改": "Save changes",
	"编辑勾选的周次": "Edit selected week",
	"取消编辑": "Cancel editing",
	"编辑模式": "Edit mode",
	"CLASS": "Course {{1}}",
	"CLASS1": "Course {{1}}",
	"添加场景排程": "Add scene course",
	"SCHEDULES": "Drag the scene to corresponding course",
	"设置": "Settings",
	"学期开始时间": "Semester start time",
	"学期结束时间": "Semester end time",
	"清除课程表": "Clear all courses",
	"DELETE_SCHEDULE": "Confirm to clear all courses timetable for the current classroom?",
	"许可内容": "License info:",
	"MAX_CONTECT": "Maximum connection desktop : {{1}}",
	"PERIOD_TIME": "Expiry date: <strong> {{1}} </strong>, left:<strong> {{2}} </strong> days",
	"更新授权": "<strong>Activate </strong>",
	"许可协议": "The license agreement",
	"ABOUT1": "<strong>The rights of usage</strong> You have the rights to install this software in computers, and use this software in the business scope to show all software features.",
	"ABOUT2": "<strong>Technical support </strong> You have the rights to obtain comprehensive technical support from OS-easy Cloud Computing. For the purposes of this software in any doubts, the problems in the process of installation, you have the rights to consult from OS-easy Cloud Computing, and request OS-easy Cloud Computing to answer or solve it.",
	"ABOUT3": "<strong>Version update </strong> According to actual needs, you have the rights to use the updated version of the software. But it is required to pay the appropriate version update fee if OS-easy Cloud Computing has other requirements.",
	"ABOUT4": "<strong>General restriction</strong> You only have the rights to use this software features, have no rights to reverse engineering, decompiling or disassembling on this software, meanwhile no rights to do secondary development, derive new software on basis of the software.",
	"ABOUT5": "<strong>Backup</strong> Unless normal use or for your own file backup purposes, you have no right to copy all or any part of the software.",
	"ABOUT6": "<strong>Usage</strong> The scope of rights to use this software is limited to your organization. without a written permission from OS-easy Cloud Computing, you have no rights to transfer, permit, rent, lease, lend or gift to others, provide the software to any third party, or reproduce any of parts of the software, whatever this offered for business purposes or not.",
	"ABOUT7": "<strong>Duty</strong> You have the duty to take effective measures to constrain your company's staff or employees to abide by the terms and conditions of the relevant conventions.",
	"ABOUT8": "<strong>Statement</strong> Refers to this software, any malicious damage to your computer resources (including documents, procedures, and other data) feature settings. For the loss of profit, availability disappeared, business interruption, or any form of indirect, special, incidental or inevitable destruction, or any other claims when you are in the process of using this software, Wuhan OS-easy Cloud Computing Co., ltd, and its agent and sale staffs is not responsible for it.",
	"ABOUT9": "<strong>Intellectual property rights and confidentiality </strong> The software copyright which involves the rights of OS-easy trademarks, patent, proprietary technology, and other rights, all are belonged to the owner of Wuhan OS-easy Cloud Computing Co., ltd. You should well keep the logo appeared in the software, cannot delete or modify without authorization. You have the rights to use it within the scope of authorization, but have no right to transfer another person to use. You also have confidentiality obligation which involves Wuhan OS-easy Cloud Computing Co., ltd’s secrets.",
	"ABOUT10": "<strong>Others</strong> Matters not included in this software license agreement will be defined in other agreement or terms consulted by both parties. This software license agreement applies to the relevant laws of the People's Republic of China.",
	"ABOUT": "If you have installed, copied or through other ways to use this software, you are deemed to have agreed with the following terms and conditions, and have signed the \"software license agreement\" (hereinafter referred to as the \"agreement\") with Wuhan OS-easy Cloud Computing Co., ltd (hereinafter referred to as the \" OS-easy Cloud Computing \"). If you obtained any copies of the software through legal channels of OS-easy Cloud Computing, then you have rights and obligations as follows:",
	"LICENSE1": "Firstly, <a href='{{1}}'> export the hardware code file </a>, and save it.",
	"LICENSE2": "Provide the hardware ID file to the software provider or access <a href = \"http://activation.os-easy.com\" target = \"_blank\" > the official authorization application site </a>, to apply the authorization document.",
	"LICENSE3": "Click the below button to upload <span style = 'color: orangered'> license.key </span>to update authorization.",
	"噢易云计算": "OS-easy Cloud Computing",
	"序号": "No.",
	"操作类型": "Operation type",
	"对象名称": "Object name",
	"开始时间": "Start Time",
	"结束时间": "End time",
	"操作人员": "Operator",
	"详细": "Detail",
	"安装方法": "Install",
	"配置硬件": "Configure  hardware",
	"第1周": "1st week",
	"第2周": "2nd week",
	"第3周": "3rd week",
	"第4周": "4th week",
	"第5周": "5th week",
	"第6周": "6th week",
	"第7周": "7th week",
	"第8周": "8th week",
	"第9周": "9th week",
	"第10周": "10th week",
	"第11周": "11th week",
	"第12周": "12th week",
	"第13周": "13th week",
	"第14周": "14th week",
	"第15周": "15th week",
	"第16周": "16th week",
	"第17周": "17th week",
	"第18周": "18th week",
	"第19周": "19th week",
	"第20周": "20th week",
	"第21周": "21th week",
	"第22周": "22th week",
	"第23周": "23th week",
	"第24周": "24th week",
	"第25周": "25th week",
	"第26周": "26th week",
	"周时间": "Termtime",
	"课程时间": "Course time",
	"/resource/host": "<ul> <li> When host is started it will automatically register to the management platform. </li> <li>After restore the deleted host, need to restart the host. </li></ul>",
	"/resource/network": "<ul> <li> Able to reset the network by network initialization</li> </ul>",
	"/desktop/scene": "<ul> <li> Teaching scene must be activated, so that its teaching desktops can only be used by the terminals. </li> <li> Multiple teaching scenes can be in activation state at the same time. </li> <li> Click on the scene can view the scenario desktop. </li> <li> There is 30 seconds remain time left when the terminals dis-connected abnormally. During the remain time, terminals can login to the original desktop. </li> <li> Delete teaching scene will interrupt and destroy all running desktops. </li> </ul>",
	"/resource/network/:id": "<ul> <li> The end of the IP can not 0, 1, 255. </li> <li> Please delete IP which cannot be used by virtual desktop from the list. </li> <li> An IP can be repeated assigned to multiple desktops, but can cause the desktop IP conflict when using IP simultaneously. </li> <li> If reset IP segment, the platform must be restarted to take effect. </li> </ul>",
	"/desktop/teach/:id": "<ul> <li>无需账号密码即可登录使用的桌面类型，提供桌面还原、计算机名修改、用户名修改等教学必须功能</li><li>激活教学场景，即可向教室内所有终端交付一套教学系统</li> </ul>",
	"/desktop/personal": "<ul><li>Personal desktop can be login at any one terminal. </li> <li> Personal desktop bind with users, need to enter your user name and password when login. </li> <li>Power-on/shutdown personal desktop can be manually controlled by the user or administrator. </li> <li> Naturally shutdown requires the system may support it, if not installed system please use the forcefully shutdown. </li> <li> Modify in batch takes effect after reboot desktop. </li> <li> Save as template, modify the desktop requires desktop in power-off state. </li> <ul>",
	"/template/teach": "<ul><li> Update template will automatically sync the template to associated teaching desktop. </ul>",
	"/template/personal": "",
	"/template/hardware": "<ul> <li> Hardware template is a shortcut to configure the virtual hardware. </li> <li> Modify hardware template will not affect the generated desktop. </li> </ul>",
	"/terminal/schoolroom": "",
	"/terminal/client": "<ul> <li> Terminal will automatically register to the management when boot. </li> <li> Remote \"Wake up\" function needs client itself hardware support \"Wake on LAN\". </li> <li>\"Login sequence number\" is refer to the terminal sequence of physical location.  </li> </ul>",
	"/terminal/session": "<ul> <li> Session connection maximum number is refer to the license stipulated by the maximum number of connections. </li> <li> Interrupt session will cut off the connection between current terminals and the desktop. </li> </ul>",
	"/user/admin": "<ul> <li> Super administrator account is “admin”, the default initial password is “admin”. </li> <li> The management platform is used by administrator only. </li> </ul>",
	"/user/common": "<ul> <li> Common user is refer to who can use of client access desktop, but can't login management platform. </li> <li>The excel format how to import the user, please reference export excel format. </li> </ul>",
	"/scheduler/view": "<ul><li>For classrooms which set default hour for teaching desktop in each class, when time arrives, will automatically activate the default desktop; </li> <li> Select the individual week time, use the edit button to enter edit mode. Drag and drop the corresponding to the corresponding class desktop; </li> <li> Select several weeks time, is taking a week as a benchmark, can edit all selected week in batch; </li> </ul>",
	"/system/backup": "<ul><li> It will cover the original backup file when file name repetition. </li><li> This function is only used for backup system database. </li></ul>",
	"/system/upgrade": "<ul> <li>The format of the system package is *. Bin.  </li> <li> Upload upgrade package, need to click on the <i class='fa fa-refresh'></i> to manual upgrade. </li> <li> after upgrading must restart the host to take effect. </li> </ul>",
	"/resource/console":"<ul><li>HA configuration requires master backup cannot be compute nodes, cannot run a virtual machine</li></ul>",
	"/resource/pool/:id":"<ul><li>对当前在线的计算节点，可以执行维护，即不受管理台控制，可以人工维护此节点</li> <li>对管理平台上已进入维护模式的在线的计算节点，可以执行恢复操作，恢复此计算节点后，之前创建的桌面不受影响</li> <li>系统会默认本地存储设备的使用策略，用户可以变更存储使用策略</li> <li>在存储模块中，添加远端存储后，可以在此处配置远端存储的使用策略</li> </ul>",
	"/resource/pool":"<ul><li>对当前在线的计算节点，可以执行维护，即不受管理台控制，可以人工维护此节点</li> <li>对管理平台上已进入维护模式的在线的计算节点，可以执行恢复操作，恢复此计算节点后，之前创建的桌面不受影响</li> <li>系统会默认本地存储设备的使用策略，用户可以变更存储使用策略</li> <li>在存储模块中，添加远端存储后，可以在此处配置远端存储的使用策略</li> </ul>",
	"/resource/storage":"<ul><li>在此处添加远端存储后，可以在资源池管理模块中配置每个计算节点的远端存储使用策略</li></ul>",
	"DEFAULT_HELP_TEXT": "No related help content",
	"DESKTOP_TOTAL_MESS": "{{1}} desktop(s) , <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown\"> </span> {{3}}",
	"每周第几天": "The day",
	"最大": "Maximum",
	"硬件信息": "Hardware information",
	"NEW_DESKTOP_EXAMPLE": "e.g: if input {{1}}, computer name will start from {{1}} 1",
	"NEW_DESKTOP_EXAMPLE2": "e.g: if input {{1}}, computer name will start from {{1}}-1",
	"DELETE_TEMPLATE_H": "Confirm to delete hardware template '{{1}}' ?",
	"DELETE_TEMPLATE_P": "Confirm to delete '{{1}}' ?",
	"DELETE_TEMPLATE_T": "Confirm to delete '{{1}}' ?",
	"皮肤一": "skin1",
	"皮肤二": "skin2",
	"TERMINAL_NAME_TIP1": "1.System will create terminal name in sequence.",
	"TERMINAL_NAME_TIP2": "2.Suggest to use short and unforgettable name for the prefix of terminal name.",
	"重启主机": "Restart host",
	"确定重启主机吗?": "Confirm to restart the host ?",
	"关闭主机": "Shut down host",
	"确定关闭主机吗": "Confirm to shut down the host ?",
	"BACKUP_DE": "Delete system backup",
	"BACKUP_DE_CONTENT": "Confirm to delete the backup?",
	"ISO_DELETE": "Delete ISO",
	"DELETE_ISO_CONTENT": "Confirm to delete the ISO?",
	"DELETE_LOG": "Delete log",
	"DELETE_LOG_CONTENT": "Confirm to delete the log(s)?",
	"DELETE_RIZHI": "Empty log(s)",
	"DELETE_RIZHI_CONTENT": "Confirm to empty the log(s)?",
	"RESTART_HOST": "Restart host",
	"RESTART_HOST_CONTENT": "Confirm to restart the host '{{1}}' ?",
	"DELETE_ALARM": "Delete alarm",
	"删除确认": "Delete terminal",
	"FIXED_IP1": "1. Assigned IP in batch  is to sequentially binding resource pool IP and client side IP",
	"FIXED_IP2": "2. Assigned IP will be no longer assigned to other client side",
	"确定删除主机吗": "Confirm to delete the host ?",
	"是否启用系统分配": "DHCP",
	"确定删除网络吗": "Confirm to delete the network?",
	"系统默认": "Default",
	"MESS_NEWPERSON5": "---- System will automatically assign available amount of IP to virtual machine",
	"查看模板": "View template",
	"MESS_NEWDESKTOP": "There is no available teaching  template!",
	"MESS_NEWDESKTOP2": "There is no available personal  template!",
	"INFOR_TIP": "Prompt",
	"选择语言": "Select Language",
	"上传系统包": "Upload",
	"上传授权文件": "Upload license",
	"导入": "Import",
	"vdiDesktopPersonalList_TIP1": "Please boot the desktop(s) in off-state",
	"vdiDesktopPersonalList_TIP2": "Please shut down the desktop(s) in running state",
	"vdiDesktopPersonalList_TIP3": "Please shut down the desktop(s) in running state",
	"vdiDesktopPersonalList_TIP4": "Please restart the desktop(s) in running state",
	"vdiDesktopPersonalList_TIP5": "Please pause the desktop(s) in running state",
	"vdiDesktopPersonalList_TIP6": "Please recover the desktop(s) in pause-state",
	"vdiDesktopTeachList_TIP1": "Please boot the desktop(s) in off-state",
	"vdiDesktopTeachList_TIP2": "Please shut down the desktop(s) in running state",
	"vdiDesktopTeachList_TIP3": "Please shut down the desktop(s) in running state",
	"vdiDesktopTeachList_TIP4": "Please restart the desktop(s) in running state",
	"vdiDesktopTeachList_TIP5": "Please pause the desktop(s) in running state",
	"vdiDesktopTeachList_TIP6": "Please recover the desktop(s) in pause-state",
	"vdiDesktopSceneList_TIP1": "The selected scene already being activated, unable to delete",
	"newSceneDialog_TIP1": "Computer name and login name must be different",
	"newSceneDialog_TIP2": "The scene name already existed",
	"newPersonDialog_TIP1": "Desktop name already existed",
	"hostMoreDialog_TIP1": "IP and gateway is not in the same network segment",
	"newNetworkManageDialog_TIP1": "The number of start IP must be smaller than end IP",
	"newNetworkManageDialog_TIP2": "VLAN ID can not be repeated",
	"newNetworkIPDialog_TIP1": "The number of start IP must be smaller than end IP",
	"删除主机": "Delete host",
	"选择": "Select",
	"删除网络": "Delete network",
	"格式化": "Formatting",
	"查看详情": "View detail",
	"剩余": "available",
	"占用率": "Utilization rate",
	"已用内存": "Used memory",
	"读取": "Write",
	"写入": "Read",
	"S_周一": "Mon",
	"S_周二": "Tue",
	"S_周三": "Wed",
	"S_周四": "Thu",
	"S_周五": "Fri",
	"S_周六": "Sat",
	"S_周日": "Sun",
	"一月": "Jan",
	"二月": "Feb",
	"三月": "Mar",
	"四月": "Apr",
	"五月": "May",
	"六月": "Jun",
	"七月": "Jul",
	"八月": "Aug",
	"九月": "Sep",
	"十月": "Oct",
	"十一月": "Nov",
	"十二月": "Dec",
	"己用内存": "Memory",
	"删除存储": "Delete storage",
	"确定删除存储吗": "Confirm to delete the storage?",
	"上行": "Upload",
	"下行": "Download",
	"vdiResourceHostList_TIP1": "Only able to restart host when it is in running state",
	"vdiResourceHostList_TIP2": "Sorry, unable to delete control node",
	"vdiResourceHostList_TIP3": "Delete host successfully",
	"vdiTemplatePresonalDesktopList_TIP1": "Unable to delete the template when it assigned to other desktop(s)",
	"vdiTemplateTeachDesktopList_TIP1": "Unable to delete the template when it assigned to other desktop(s)",
	"vdiTerminalClientManage_TIP1": "Unable to set operation parameters when the terminal has been shut down",
	"vdiTerminalClientManage_TIP2": "Only able to set parameters when the machine is in running state",
	"vdiTerminalClientManage_TIP3": "Unable to modify terminal name when it has been shut down,",
	"vdiTerminalClientManage_TIP4": "Only able to modify terminal in running state",
	"vdiTerminalClientManage_TIP5": "Please select terminal",
	"vdiTerminalClientManage_TIP6": "The terminal has been waked up",
	"vdiTerminalClientManage_TIP7": "The terminal has been powered off",
	"vdiTerminalClientManage_TIP8": "Unable to terminate session when the terminal has been shut down",
	"vdiTerminalClientManage_TIP9": "Unable to delete when the terminal is in running state",
	"vdiTerminalClientManage_TIP10": "Unable to delete classroom when there is scene and terminal existed",
	"中断确认": "Terminate session",
	"Flash 插件没有安装": "Flash plugin is not installed",
	"文件名已存在": "The file name already exists",
	"上传的版本低于现在的版本": "The uploaded version is lower than the current version",
	"授权更新成功": "Update authorization successed",
	"授权更新失败": "Update authorization failed",
	"LICENSE_MESS_1": "New authorization has been taken effect, please view it after close this window and refresh the page.",
	"LICENSE_MESS_2": "Authorization file isn't matching to server hardware ID, please upload again after confirmation.",
	"LICENSE_MESS_3": "It is not a legal authorization file format or content, please check and upload again.",
	"删除IP": "Delete IP",
	"确定删除IP吗": "Confirm to delete the IP?",
	"项结果": " ",
	"存在未关机的桌面，仍然删除桌面吗": "There is desktop in running state , confirm to delete the desktop ?",
	"模板系统盘不能为0": "The system disk of template cannot be 0",
	"检查安装环境": "Check Environment",
	"系统初始化": "Initialization",
	"开始初始化": "Begin Initialize",
	"当前安装的版本为": "Current Version",
	"服务器": "Server",
	"导入默认数据": "Import Data",
	"建立超级管理员账户": "Import Administrator Account",
	"建立Projects": "Import Projects",
	"建立本地存储": "Import Local Disk",
	"建立默认教室": "Import Classroom",
	"建立默认硬件模板": "Import Hardware Template",
	"初始化客户端配置": "Import Client Configuration",
	"初始化网络": "Import Network",
	"初始化学期": "Initialize Semester",
	"MESS_INIT__FINISH": "Congratulations on system initialization is complete!<br>\n You can now",
	"登录": "Login",
	"第30周": "30th week",
	"第31周": "31th week",
	"第32周": "32th week",
	"第33周": "33th week",
	"第34周": "34th week",
	"第35周": "35th week",
	"第36周": "36th week",
	"第37周": "37th week",
	"第38周": "38th week",
	"第39周": "39th week",
	"第40周": "40th week",
	"进入管理台": "login as \"admin\"",
	"关机确认": "Shutdown terminal",
	"非系统盘": "Non-system disk",
	"不可重复添加已存在IP": "Existed IP will not be added repeatedly",
	"新增成功": "New IP added successfully!",
	"请输入合法数据": "Please enter valid data",
	"STORAGE_MESS": "{{1}} has been used by {{2}}({{3}})!",
	"文件不会被添加到队列中": "The file will not be added to the queue",
	"QUEUE_LIMIT_EXCEEDED": "The selected file number exceeds the upload limit ({{1}})",
	"INVALID_FILETYPE": "file:{{1}} \n'{{2}}' is not an accepted file type",
	"ZERO_BYTE_FILE": "File:{{1}} \nis empty！",
	"FILE_EXCEEDS_SIZE_LIMIT": "{{1}}\nexceeded file size limit {{2}}",
	"QUEUE_LIMIT_EXCEEDED2": "The number of your select file more than the queue size limit",
	"取消登录序号": "Cancel login sequence",
	"CANCEL_LOGINNUM": "Confirm to cancel login sequence?",
	"第27周": "27th week",
	"第28周": "28th week",
	"第29周": "29th week",
	"INSTALLED": "installation is complete",
	"高级管理": "Advance management",
	"选择网卡": "Choose NIC",
	"waringtype1": "Prompt",
	"waringtype0": "Warning",
	"waringtype-1": "Error",
	"操作结果": "Result message",
	"桌面重置": "Reset desktop",
	"确定重置桌面吗": "Confirm to reset the desktop?",
	"重置成功": "Reset successfully",
	"CLIENTMODIFY_SHUT": "Confirm to shut down ?",
	"CLIENT_TIP7": "Terminal has no access to the desktop",
	"SYSISOTIP1": "Please set the system type of ISO in system ISO first",
	"SYSISOTIP2": "There is no auto-install ISO",
	"1~10位英文和数字": "1 ~ 10 letters or digits",
	"INFOR_UPISO": "Begin to upload,please don't leave the page!",
	"ADMIN_TIP": "The user binded with desktop, unable to delete",
	"USER_TIPGROUP2": "'{{1}}' associated with other desktop and can not be deleted",
	"域用户": "Domain user",
	"域名": "Domain name",
	"服务器地址": "Server address",
	"域管理员": "Domain administrator",
	"关联用户数": "Associated users",
	"DOMAIN_TOTAL_MESS": "{{1}} domain(s), <span class = \"status16 running\"> </span> {{2}} , <span class = \"status16 shutdown\"> </span> {{3}}",
	"新增域控制器": "Add Domain Controller",
	"域控制器": "Domain Controller",
	"同步域用户": "Syncing domain user",
	"一键同步": "One button",
	"自定义同步": "Custom",
	"域登录名": "Domain username",
	"分组名": "Group Name",
	"编辑域控制器": "Edit domain Controller",
	"删除域控制器": "Delete domain Controller",
	"删除域用户": "Delete domain user",
	"更新域用户": "Update domain user",
	"选择分组": "Choose groups",
	"已选分组": "Chosed groups",
	"包含子目录": "Include subdirectories",
	"请选择需要同步的域分组": "Please select a domain packet synchronization:",
	"加入域": "Domain support",
	"所属域": "Domain",
	"SYNC_TEM": "Sync template",
	"SYNC_TEM_TIP": "Update desktop will close all the desktops associated with the current template and then update them all, Confirm to update desktop?",
	"USB_GROUP": "Class",
	"PID_LIMIT": "-1 or four hexadecimal number",
	"IS_REDIRECT": "Redirection",
	"USB_TYPE": "Type",
	"USB 重定向": "USB redirection",
	"/scheduler/edit": "",
	"资源": "Resource",
	"主控": "Console",
	"子网": "Subnet",
	"系统盘存储": "System disk storage",
	"数据盘存储": "Data disk storage",
	"倒数": "count backwards",
	"自动进入": "auto log in",
	"hybirdTip": "Tips: countdown 5 seconds at least,not more than 600 seconds",
	"自动进入桌面倒计时": "Auto log in desktop countdown",
	"个人桌面启用": "Personal desktop enabled",
	"教学桌面启用": "Teach desktop enabled",
	"MODE_TIP": "Note: In window mode, only close desktop while closing terminal in Teaching desktop shutdown mode effective, other desktop shutdown strategy is not effective",
	"高可用性": "HA",
	"桌面HA":"Desktop HA",
	"场景属性":"Scene properties ",
	"运行配置":"Running configuration",
	"网络配置":"Network configuration",
	"宿主机配置":"Host configuration",
	"桌面属性":"Desktop properties",
	"修改模板": "Modify template",
	"固定IP": "Fixed IP",
	"系统盘镜像": "System disk image",
	"数据盘镜像": "Data disk image",
	"无": "None",
	"场景排序":"Sort",
	"请选择一个教学模板":"Please select a teaching template",
	"域设置":"Domain",
	"请选择":"Please select",
	"计算":"Agent",
	"新增子网":"新增子网",
	"资源池名称":"资源池名称",
	"主机数量":"主机数量",
	"添加存储":"添加存储",
	"子网数量":"子网数量",
	"管理网络初始化":"管理网络初始化",
	"选择管理网络":"选择管理网络",
	"维护":"维护",
	"HA配置":"HA配置",
	"配置主控HA策略":"配置主控HA策略",
	"主控HA":"主控HA",
	"主控节点管理IP":"主控节点管理IP",
	"备控节点管理IP":"备控节点管理IP",
	"备控节点管理账户":"备控节点管理账户",
	"数据同步网络":"数据同步网络",
	"浮动IP":"浮动IP",
	"仲裁IP":"仲裁IP",
	"敏感度(秒)":"敏感度(秒)",
	"测试连接":"测试连接",
	"资源池名称":"资源池名称",
	"主机数量":"主机数量",
	"添加计算节点":"添加计算节点",
	"配置存储":"配置存储",
	"本地网络":"本地网络",
	"本地存储":"本地存储",
	"网卡类型":"网卡类型",
	"磁盘":"磁盘",
	"总容量()":"总容量{{1}}",
	"可用空间()":"可用空间{{1}}",
	"品牌":"品牌",
	"硬盘":"硬盘",
	"MESS_MAXSETINSTANCE":"可同时创建最大桌面数",
	"基础镜像存储设备":"基础镜像存储设备",
	"存储设备":"存储设备",
	"性能型存储设备":"性能型存储设备",
	"容量型存储设备":"容量型存储设备",
	"配置存储设备使用策略":"配置存储设备使用策略",
	"远端存储":"远端存储",
	"已分配存储":"已分配存储",
	"未分配存储":"未分配存储",
	"详情":"Detail",
	"维护中...":"维护中...",
	"创建中...":"创建中...",
	"分配类型":"分配类型",
	"子网名称":"子网名称",
	"网络名称":"网络名称",
	"创建子网":"创建子网",
	"编辑网络":"编辑网络",
	"DELETE_NETWORK_COMFIRM":"删除网络将删除该网络下的所有子网，桌面将无法使用该网络，确认删除吗？",
	"DELETE_SUB_NETWORK_COMFIRM":"删除子网后，桌面将无法使用该子网，确认删除吗？",
	"外设配置":"外设配置",
	"系统分配":"系统分配",
	"新增网络":"新增网络",
	"编辑子网":"编辑子网",
	"策略名称":"策略名称",
	"响应时间":"响应时间",
	"启用状态":"启用状态",
	"策略描述":"策略描述",
	"选择桌面":"选择桌面",
	"中":"中",
	"低":"低",
	"高":"高",
	"确定维护主机吗":"确定维护主机吗",
	"确定恢复主机吗":"确定恢复主机吗",
	"维护主机":"维护主机",
	"上移":"上移",
	"下移":"下移",
	"SCHO0L":"教室",
	"域用户列表": "Domain user list",
	"此资源池无可用主机":"此资源池无可用主机",
	"设置主控节点":"设置主控节点",
	"管理服务器IP":"管理服务器IP",
	"INIT_COSOLE_MESS":"INIT_COSOLE_MESS",
	"INIT_AGENT_MESS":"INIT_AGENT_MESS",
	"INIT_CONSOLE_LOADDING_MESS":"正在设置主控中，这个过程需要大约5分钟时间，请稍候！",
	"主控设置":"主控设置",
	"将该主控添加为计算节点":"将该主控添加为计算节点",
	"重置模板":"重置模板",
	"REST_TEMP_TIP":"重置模板将会删除原模板虚拟机,重新创建模板虚拟机,是否确定?",
	"筛选":"筛选",
	"上传包类型":"上传包类型",
	"清除消息":"清除消息",
	"消息":"消息",
	"均衡创建":"均衡创建",
	"桌面计算机名/用户名":"桌面计算机名/用户名",
	"INIT_AGENT_LOADDING_MESS":"正在添加计算节点，请稍候！",
	"终端教学桌面":"教学桌面",
	"终端个人桌面":"个人桌面",
	"REGISTER_TIP":"正在注册，可关闭窗口进行其他操作",
	"系统桌面":"系统桌面",
	"新增系统桌面":"Add System Desktop",
	"系统桌面类型":"Type",
	"分布式文件系统服务器":"Distributed File System Server",
	"普通服务器":"Normal Server",
	"上传镜像":"Upload image",
	"创建桌面":"Create",
	"查看桌面详情":"View",
	"另存为":"Save as",
	"删除服务器":"Delete Server",
	"DELETE_SYSDESK_T":"Confirm to delete '{{1}}' ?",
	"系统桌面设置":"系统桌面设置",
	"选择透传设备":"选择透传设备",
	"启动":"启动",
	"随宿主机服务器启动":"随宿主机服务器启动",
	"配置桌面":"配置桌面",
	"编辑桌面":"编辑桌面",
	"桌面详情":"桌面详情",
	"分布式存储服务器":"分布式存储服务器",
	"普通服务器":"普通服务器",
	"vdiResourceHostList_TIPRECOVER":"只能对维护状态的主机执行恢复操作",
	"无设备":"无设备",
	"vdiDesktopTeachList_TIP7":"请对关机状态的桌面执行修改操作",
	"取消PCI设备透传":"取消PCI设备透传",
	"未启用":"未启用",
	"解绑":"解绑",
	"OUTER_IP_NOTE":"<p>说明</p> <p>1.在路由器上设置地址转换之后，需要在此处保存外网IP，才能通过公网使用所有功能。</p> <p>2.如果服务器网卡配置了外网IP，需要在此处保存此外网IP，才能通过公网使用所有功能。<p>",
	"vdiResourceHostList_TIPDELETE":"请确定主机处于在线状态，且主机不存在虚拟机",
	"vdiResourceHostList_TIPACTIVE":"请确定主机处于在线状态",
	"REGISTER_FAILED":"Register failed",
	"CLONING_FAILED":"Cloning failed",
	"RESET_FAILED":"Reset failed",
	"CREATE_FAILED":"Create failed",
	"主控管理":"主控管理",
	"资源池管理":"资源池管理",
	"新增资源池":"新增资源池",
	"配置属性":"配置属性",
	"--请选择--":"-请选择-",
	"继承网卡":"继承网卡",
	"解绑网卡":"解绑网卡",
	"绑定网卡":"绑定网卡",
	"bond类型":"bond类型",
	"NETCARD":"网卡",
	"SCENE_CANCEL_COMFIRM":"取消激活该场景会同时关闭该场景内的所有桌面，是否确定?",
	"DELETE_HOST_COMFIRM":"当计算节点在线且没有桌面和模板或计算节点不在线时，才能够被删除，是否确定？",
	"MAINTAIN_HOST_COMFIRM":"进入维护模式时，会关闭当前计算节点上的所有桌面，是否确定？",
	"桌面移动成功":"桌面移动成功",
	"vdiBondNetcard_TIP1":"请至少选择两张网卡进行绑定",
	"HA_NOTE":"启用HA时，此IP会被设置为浮动IP",
	"对象": "Object",
	"rescheduled": "执行了HA策略",
	"存储用途":"存储用途",
	"桌面磁盘镜像存储":"桌面磁盘镜像存储",
	"本地文件共享存储":"本地文件共享存储",
	"存储管理节点":"存储管理节点",
	"无可绑定网卡":"无可绑定网卡",
	"LIMITE_LETTER":"2～20位英文和数字，必须以英文开头",
	"配置公共存储":"配置公共存储",
	"禁用":"禁用",
	"INIT_COMPUTENODE_MESS":"当前主机已被添加为备控或计算节点，不能执行初始化；如果要将当前节点设置为主控，请在原管理台上删除该节点或联系管理员。",
	"TEM_CONFIG_TIP":"注：修改CPU和内存在虚拟机下次开机后生效",
	"MASKMODEL_WAITING_TIPS":"正在重启服务，请稍候",
	"DESKTOP_MOVE_TIP1":"请选择远端存储上的已关机的KVM类型桌面进行移动",
	"SAVING": "Saving ...",
	"文件浏览":"文件浏览",
	"vdiDesktopPersonalDomain_TIP1":"请选择未加入域的桌面",
	"vdiDesktopPersonalDomain_TIP2":"请选择已加入域的桌面",
	"DOMAIN_EXIT_TIP":"所选桌面在下一次开机时，将自动执行退域的操作，是否确定？",
	"DOMAIN_EXIT_TIP2":"该场景下的所有桌面在下一次开机时，将自动执行退域的操作，是否确定？",
	"加域":"加域",
	"退域":"退域",
	"MESS_DOMAIN_LABEL":"请选择需要加入的域",
	"MESS_DOMAIN_SID":"修改桌面计算机安全标志符（SID）",
	"MESS_DOMAIN_CONTROLLER":"不存在域控制器！",
	"拟加入域":"拟加入域",
	"当前域":"当前域",
	"域":"域",
	"总容量":"总容量",
	"镜像管理":"镜像管理",
	"镜像类型":"镜像类型",
	"是否存在镜像":"是否存在镜像",
	"是否关联桌面":"是否关联桌面",
	"管理主机":"管理主机",
	"简体中文":"简体中文",
	"繁体中文":"繁体中文",
	"所在宿主机":"所在宿主机",
	"宿主机分布":"宿主机分布",
	"HA宿主机范围":"HA宿主机范围",
	"所有桌面数":"所有桌面数",
	"MESS_NEW_HA":"说明：此处筛选出有与原宿主机相同的网络、镜像和存储配置的HA宿主机",
	"分发镜像":"分发镜像",
	"删除镜像":"删除镜像",
	"正在删除":"正在删除...",
	"正在分发":"正在分发...",
	"分发失败":"分发失败!",
	"重新分发":"重新分发",
	"存储控制节点":"存储控制节点",
	"自定义创建":"自定义创建",
	"数据盘还原":"数据盘还原",
	"正在请求":"正在请求...",
	"查看桌面HA详情":"查看桌面HA详情",
	"修改桌面计算机名":"修改桌面计算机名",
	"删除系统桌面":"删除系统桌面",
	"TEM_EXIST":"该模板存在关联的个人桌面，不能更新",
	"存储详情":"存储详情",
	"计划任务":"计划任务",
	"定时开关机":"定时开关机",
	"模板详情":"模板详情",
	"任务名":"任务名",
	"新增定时开关机":"新增定时开关机",
	"时":"时",
	"分":"分",
	"执行时间":"执行时间（每天）",
	"执行任务":"执行任务",
	"数据盘镜像2":"数据盘镜像2",
	"告警策略": "告警策略",
	"GPU加速": "GPU加速",
	"卷ID": "卷ID",
	"备份配置":"备份配置",
	"保留数量":"保留数量",
	"自动备份":"自动备份",
	"备份周期":"备份周期",
	"每天":"每天",
	"每周":"每周",
	"备份时间":"备份时间",
	"备份路径":"备份路径",
	"启用GPU加速":"启用GPU加速",
	"启用USB":"启用USB",
	"SHUTOFF_TIP":"模板虚拟机已关机",
	"shutdown_TEMPLATE_T":"Confirm to shutdown '{{1}}' template virtual machine?",
	"无可挂载数据盘":"无可挂载数据盘",
	"是否自动进入桌面":"是否自动进入桌面",
	"设置自动进入桌面":"自动进入桌面",
	"倒计时":"倒计时",
	"未获取到信息":"未获取到信息",
	"显卡":"显卡",
	"设置桌面IP":"设置桌面IP",
	"取消桌面IP":"取消绑定桌面IP",
	"CANCELIP_TIP":"绑定桌面IP已取消",
	"CANCELIP_TIP1":"确定取消绑定终端 '{{1}}' 的桌面IP?",
	"未获取到信息":"未获取到信息",
	"编辑定时开关机":"编辑定时开关机",
	"DELETE_PLAN_T":"确定删除任务 '{{1}}' ?",
	"DELE_PLAN_TIP":"不能删除正在执行的任务",
	"确认删除吗":"确认删除吗?",
	"系统保留的备份文件数量":"系统保留的备份文件数量",
	"备份方式":"备份方式",
	"手动备份":"手动备份",
	"已启用":"已启用",
	"MONITOR_EMAILL_MESS":"如果有多个邮箱地址，每个邮箱地址单独占一行",
	"更多详情":"更多详情",
	"TIP_PLAN":"说明：此处开机任务为唤醒教学桌面对应的终端",
	"hasStaticIP_TIP": "无可用IP",
	
	"SCHEDUL_TIP":"Boot and shutdown time is the same",
	"确认删除存储吗":"确认删除存储吗",
	"执行格式化":"执行格式化",
	"主控节点当前管理IP":"主控节点当前管理IP",
	"主控节点新管理IP":"主控节点新管理IP",
	"删除失败":"删除失败",
	"新增bond":"新增bond",
	"网络类型":"网络类型",
	"系统盘镜像存储设备":"系统盘镜像存储设备",
	"数据盘镜像存储设备":"数据盘镜像存储设备",
	"系统盘存储设备":"系统盘存储设备",
	"数据盘存储设备":"数据盘存储设备",
	"主机缓存设备":"主机缓存设备",
	"镜像存储":"镜像存储",
	"增加":"Add",
	"删除2":"Delete",
	"配置全局告警":"配置全局告警",
	"配置告警邮件":"配置告警邮件",
	"告警项":"告警项",
	"CPU利用率":"CPU利用率",
	"内存利用率":"内存利用率",
	"磁盘使用空间":"磁盘使用空间",
	"磁盘IO利用率":"磁盘IO利用率",
	"网络上下行速率":"网络上下行速率",
	"持续":"持续",
	"告警邮件":"告警邮件",
	"发送告警邮件":"发送告警邮件",
	"新增告警策略":"新增告警策略",
	"分钟":"分钟",
	"核心服务异常":"核心服务异常",
	"计算节点离线":"计算节点离线",
	"主控高可用性":"主控高可用性",
	"桌面高可用性":"桌面高可用性",
	"教学桌面运行时间":"教学桌面运行时间",
	"个人桌面运行时间":"个人桌面运行时间",
	"系统授权日期":"系统授权日期",
	"小时":"小时",
	"天":"天",
	"发件服务器地址":"发件服务器地址",
	"发件人邮箱账户":"发件人邮箱账户",
	"发件人邮箱密码":"发件人邮箱密码",
	"测试邮件地址":"测试邮件地址",
	"发送测试邮件":"发送测试邮件",
	"查看告警策略":"查看告警策略",
	"不发送告警邮件":"不发送告警邮件",
	"修改告警策略":"修改告警策略",
	"移动至":"移动至",
	"计算机名":"计算机名",
	"挂载数据盘":"挂载数据盘",
	"虚拟化类型":"虚拟化类型",
	"场景创建中":"场景创建中",
	"IP池":"IP池",
	"DELETE_HOST_COMFIRM?":"当计算节点在线且没有桌面和模板或计算节点不在线时，才能够被删除，是否确定？",
	"物理网络":"物理网络",
	"取消场景激活":"取消场景激活",
	"应用":"应用",
	"删除数据盘":"删除数据盘",
	"无可用个人桌面":"无可用个人桌面",
	"选择目标主机":"选择目标主机",
	"桌面计算机名":"桌面计算机名",
	"教学场景": "教学场景",
	"立即备份":"立即备份",
	"桌面移动":"桌面移动",
	"DELETE_POOL_COMFIRM":"确定删除资源池吗？",
	"INIT_COSOLE_MESS2":"1.管理网络是指主控节点与计算节点上所有服务之间通信的网络,2.镜像网络是指主控节点与计算节点上分发镜像使用的网络",
	"创建数据网络":"创建数据网络",
	"映射网络适配器":"映射网络适配器",
	"分布式虚拟交换机":"分布式虚拟交换机",
	"数据网络":"数据网络",
	"分布式虚拟交换机名称":"分布式虚拟交换机名称",
	"镜像网络":"镜像网络",
	"按创建时间排序":"按创建时间排序",
	"按模板名称排序":"按模板名称排序",
	"管理网络":"管理网络",
	"分布式虚拟交换机":"分布式虚拟交换机",
	"数据网络":"数据网络",
	"修改管理网络":"修改管理网络",
	"修改镜像网络":"修改镜像网络",
	"修改":"修改",
	"主机名":"主机名",
	"网络类型":"网络类型",
	"关联主机":"关联主机",
	"映射网络适配器":"映射网络适配器",
	"编辑分布式虚拟交换机":"编辑分布式虚拟交换机",
	"删除分布式虚拟交换机":"删除分布式虚拟交换机",
	"DELETE_VIRTUALSWITCH":"DELETE_VIRTUALSWITCH",
	"透传":"透传",
	"设备名称":"设备名称",
	"设备制造商":"设备制造商",
	"所属主机":"所属主机",
	"透传到桌面":"透传到桌面",
	"后台日志":"后台日志",
	"主机 USB 设备":"主机 USB 设备",
	"映射网卡":"映射网卡",
	"ADD_AGENT_MESS":"---添加计算节点的说明",
	"ADD_AGENT_NOTE":"请务必在该计算节点上配置与该IP能够通信的镜像网络IP，否则创建桌面或更新模板会失败",
	"重新发现":"重新发现",
	"映射网络设备器":"映射网络设备器",
	"关联分布式虚拟交换机":"关联分布式虚拟交换机",
	"立即进入":"立即进入",
	"首选":"首选",
	"备用":"备用",
	"确认删除该bond设备吗":"确认删除该bond设备吗",
	"继承IP":"继承IP",
	"现有IP":"现有IP",
	"指派网卡":"指派网卡",
	"D_UNBUNDLE_NETCARD_EXPLAIN1":"为保持网络的连通性，可以继承IP",
	"D_UNBUNDLE_NETCARD_EXPLAIN2":"管理网络和镜像网络必须继承",
	"新增bond":"新增bond",
	"外网访问":"外网访问",
	"NO_OUSIDEIP":"无可用计算节点",
	"上传":"上传",
	"上传安装包":"上传安装包",
	"添加文件":"添加文件",
	"本地网卡":"本地网卡",
	"编辑映射网络适配器":"编辑映射网络适配器",
	"新增分布式虚拟交换机":"新增分布式虚拟交换机",
	"删除资源池":"删除资源池",
	"编辑资源池":"编辑资源池",
	"Windows客户端1":"Windows客户端",
	"等待时间":"等待时间",
	"与服务器连接断开后自动退出":"与服务器连接断开后自动退出",
	"测试镜像网络":"测试镜像网络",
	"网络不通":"网络不通",
	"网络堵塞":"网络堵塞",
	"网络连通":"网络连通",
	"选择路径":"选择路径",
	"新增关联主机":"新增关联主机",
	"删除关联主机":"删除关联主机",
	"DELETE_VIRTUALSWITCHITEM":"删除该关联主机后，如果在该主机上创建桌面，则无法使用分布式虚拟交换机上的网络，确定删除吗？",
	"无可用的关联主机网卡":"无可用的关联主机与网卡",
	"USB_NOTE":"说明：当桌面操作系统为windows 7及其以上版本,才能启用USB3.0重定向",
	"资源池删除":"资源池删除",
	"外网IP123":"代理服务器IP",
	"编辑bond":"编辑bond",
	"vdi_checkping_error":"获取到网卡信息失败",
	"主控节点/计算节点":"主控节点/计算节点",
	"Hyper-V桌面连接方式":"Hyper-V桌面连接方式",
	"terminalTips":"<ul> <li>设置windows客户端连接Hyper-V类型的桌面时的连接方式：</li> <br> <li>RDP：</li><li>1.终端和桌面均只支持windows 7及以上操作系统</li><li>2.终端与远程桌面需要能够通讯，可以根据网络速率自动调整连接质量</li><li>3.连接过程中，桌面的网络不能被更改，否则连接会断开</li><li>4.原生支持本地视频重定向</li> <br><li>VMConnect：</li><li>1.终端和桌面均只支持windows 8及以上操作系统</li><li>2. 终端需要打开hyper-v功能</li></ul>",
	"DELETE_BOND_IVALID_CONFIRM":"网卡未启用，可能会造成相关服务无法响应，是否确定？",
	"镜像网络无法连通":"镜像网络无法连通",
	"configHATestIPConfirm":"请先点击'测试连接'按钮，确认仲裁IP网络连通",
	"关闭排序":"关闭",
	"随宿主机启动":"随宿主机启动",
	"登录用户名":"用户名",
	"磁盘共享到桌面": "磁盘共享到桌面",
	"资源回收":"资源回收",
	"时间同步":"时间同步",
	"断开连接":"断开连接",
	"after-minutes":"分钟后，",
	"挂起":"挂起",
	"更改":"更改",
	"after-hours":"小时后，",
	"与Internet时间服务器同步(s)":"与Internet时间服务器同步(s)",
	"服务器(E):":"服务器(E):",
	"立即同步":"立即同步",
	"同步时间成功":"同步时间成功",
	"时区":"时区",
	"关机提示":"关机提示",
	"是否进行一键关机？":"是否进行一键关机？",
	"执行周期":"执行周期"

}
